// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	"github.com/gorilla/sessions"
	mock "github.com/stretchr/testify/mock"
)

// NewMockICookieService creates a new instance of MockICookieService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICookieService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICookieService {
	mock := &MockICookieService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockICookieService is an autogenerated mock type for the ICookieService type
type MockICookieService struct {
	mock.Mock
}

type MockICookieService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICookieService) EXPECT() *MockICookieService_Expecter {
	return &MockICookieService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockICookieService
func (_mock *MockICookieService) Get(r *http.Request, name string) (*sessions.Session, error) {
	ret := _mock.Called(r, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *sessions.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string) (*sessions.Session, error)); ok {
		return returnFunc(r, name)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request, string) *sessions.Session); ok {
		r0 = returnFunc(r, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sessions.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request, string) error); ok {
		r1 = returnFunc(r, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICookieService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockICookieService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - r *http.Request
//   - name string
func (_e *MockICookieService_Expecter) Get(r interface{}, name interface{}) *MockICookieService_Get_Call {
	return &MockICookieService_Get_Call{Call: _e.mock.On("Get", r, name)}
}

func (_c *MockICookieService_Get_Call) Run(run func(r *http.Request, name string)) *MockICookieService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICookieService_Get_Call) Return(session *sessions.Session, err error) *MockICookieService_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockICookieService_Get_Call) RunAndReturn(run func(r *http.Request, name string) (*sessions.Session, error)) *MockICookieService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockICookieService
func (_mock *MockICookieService) Save(ses *sessions.Session, r *http.Request, w http.ResponseWriter) error {
	ret := _mock.Called(ses, r, w)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*sessions.Session, *http.Request, http.ResponseWriter) error); ok {
		r0 = returnFunc(ses, r, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICookieService_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockICookieService_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ses *sessions.Session
//   - r *http.Request
//   - w http.ResponseWriter
func (_e *MockICookieService_Expecter) Save(ses interface{}, r interface{}, w interface{}) *MockICookieService_Save_Call {
	return &MockICookieService_Save_Call{Call: _e.mock.On("Save", ses, r, w)}
}

func (_c *MockICookieService_Save_Call) Run(run func(ses *sessions.Session, r *http.Request, w http.ResponseWriter)) *MockICookieService_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sessions.Session
		if args[0] != nil {
			arg0 = args[0].(*sessions.Session)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 http.ResponseWriter
		if args[2] != nil {
			arg2 = args[2].(http.ResponseWriter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockICookieService_Save_Call) Return(err error) *MockICookieService_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICookieService_Save_Call) RunAndReturn(run func(ses *sessions.Session, r *http.Request, w http.ResponseWriter) error) *MockICookieService_Save_Call {
	_c.Call.Return(run)
	return _c
}
