// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/jackc/pgx/v5/pgxpool"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIDatabase creates a new instance of MockIDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDatabase {
	mock := &MockIDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIDatabase is an autogenerated mock type for the IDatabase type
type MockIDatabase struct {
	mock.Mock
}

type MockIDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDatabase) EXPECT() *MockIDatabase_Expecter {
	return &MockIDatabase_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockIDatabase
func (_mock *MockIDatabase) Close() {
	_mock.Called()
	return
}

// MockIDatabase_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIDatabase_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIDatabase_Expecter) Close() *MockIDatabase_Close_Call {
	return &MockIDatabase_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIDatabase_Close_Call) Run(run func()) *MockIDatabase_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabase_Close_Call) Return() *MockIDatabase_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIDatabase_Close_Call) RunAndReturn(run func()) *MockIDatabase_Close_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockIDatabase
func (_mock *MockIDatabase) Get() *pgxpool.Pool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *pgxpool.Pool
	if returnFunc, ok := ret.Get(0).(func() *pgxpool.Pool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgxpool.Pool)
		}
	}
	return r0
}

// MockIDatabase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIDatabase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockIDatabase_Expecter) Get() *MockIDatabase_Get_Call {
	return &MockIDatabase_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockIDatabase_Get_Call) Run(run func()) *MockIDatabase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDatabase_Get_Call) Return(pool *pgxpool.Pool) *MockIDatabase_Get_Call {
	_c.Call.Return(pool)
	return _c
}

func (_c *MockIDatabase_Get_Call) RunAndReturn(run func() *pgxpool.Pool) *MockIDatabase_Get_Call {
	_c.Call.Return(run)
	return _c
}
