// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIFileService creates a new instance of MockIFileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIFileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIFileService {
	mock := &MockIFileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIFileService is an autogenerated mock type for the IFileService type
type MockIFileService struct {
	mock.Mock
}

type MockIFileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIFileService) EXPECT() *MockIFileService_Expecter {
	return &MockIFileService_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type MockIFileService
func (_mock *MockIFileService) Save(filename string, content io.Reader) (string, error) {
	ret := _mock.Called(filename, content)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, io.Reader) (string, error)); ok {
		return returnFunc(filename, content)
	}
	if returnFunc, ok := ret.Get(0).(func(string, io.Reader) string); ok {
		r0 = returnFunc(filename, content)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, io.Reader) error); ok {
		r1 = returnFunc(filename, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFileService_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockIFileService_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - filename string
//   - content io.Reader
func (_e *MockIFileService_Expecter) Save(filename interface{}, content interface{}) *MockIFileService_Save_Call {
	return &MockIFileService_Save_Call{Call: _e.mock.On("Save", filename, content)}
}

func (_c *MockIFileService_Save_Call) Run(run func(filename string, content io.Reader)) *MockIFileService_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIFileService_Save_Call) Return(s string, err error) *MockIFileService_Save_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIFileService_Save_Call) RunAndReturn(run func(filename string, content io.Reader) (string, error)) *MockIFileService_Save_Call {
	_c.Call.Return(run)
	return _c
}
