// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIFileService creates a new instance of MockIFileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIFileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIFileService {
	mock := &MockIFileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIFileService is an autogenerated mock type for the IFileService type
type MockIFileService struct {
	mock.Mock
}

type MockIFileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIFileService) EXPECT() *MockIFileService_Expecter {
	return &MockIFileService_Expecter{mock: &_m.Mock}
}

// GeneratePresignURL provides a mock function for the type MockIFileService
func (_mock *MockIFileService) GeneratePresignURL(ctx context.Context, param domain.GeneratePresignURLParam) (*domain.GeneratePresignURLReturn, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePresignURL")
	}

	var r0 *domain.GeneratePresignURLReturn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GeneratePresignURLParam) (*domain.GeneratePresignURLReturn, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GeneratePresignURLParam) *domain.GeneratePresignURLReturn); ok {
		r0 = returnFunc(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GeneratePresignURLReturn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.GeneratePresignURLParam) error); ok {
		r1 = returnFunc(ctx, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFileService_GeneratePresignURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePresignURL'
type MockIFileService_GeneratePresignURL_Call struct {
	*mock.Call
}

// GeneratePresignURL is a helper method to define mock.On call
//   - ctx context.Context
//   - param domain.GeneratePresignURLParam
func (_e *MockIFileService_Expecter) GeneratePresignURL(ctx any, param any) *MockIFileService_GeneratePresignURL_Call {
	return &MockIFileService_GeneratePresignURL_Call{Call: _e.mock.On("GeneratePresignURL", ctx, param)}
}

func (_c *MockIFileService_GeneratePresignURL_Call) Run(run func(ctx context.Context, param domain.GeneratePresignURLParam)) *MockIFileService_GeneratePresignURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.GeneratePresignURLParam
		if args[1] != nil {
			arg1 = args[1].(domain.GeneratePresignURLParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIFileService_GeneratePresignURL_Call) Return(generatePresignURLReturn *domain.GeneratePresignURLReturn, err error) *MockIFileService_GeneratePresignURL_Call {
	_c.Call.Return(generatePresignURLReturn, err)
	return _c
}

func (_c *MockIFileService_GeneratePresignURL_Call) RunAndReturn(run func(ctx context.Context, param domain.GeneratePresignURLParam) (*domain.GeneratePresignURLReturn, error)) *MockIFileService_GeneratePresignURL_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiles provides a mock function for the type MockIFileService
func (_mock *MockIFileService) ListFiles(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFileService_ListFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiles'
type MockIFileService_ListFiles_Call struct {
	*mock.Call
}

// ListFiles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIFileService_Expecter) ListFiles(ctx any) *MockIFileService_ListFiles_Call {
	return &MockIFileService_ListFiles_Call{Call: _e.mock.On("ListFiles", ctx)}
}

func (_c *MockIFileService_ListFiles_Call) Run(run func(ctx context.Context)) *MockIFileService_ListFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIFileService_ListFiles_Call) Return(strings []string, err error) *MockIFileService_ListFiles_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockIFileService_ListFiles_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockIFileService_ListFiles_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockIFileService
func (_mock *MockIFileService) Save(filename string, content io.Reader) (string, error) {
	ret := _mock.Called(filename, content)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, io.Reader) (string, error)); ok {
		return returnFunc(filename, content)
	}
	if returnFunc, ok := ret.Get(0).(func(string, io.Reader) string); ok {
		r0 = returnFunc(filename, content)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, io.Reader) error); ok {
		r1 = returnFunc(filename, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIFileService_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockIFileService_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - filename string
//   - content io.Reader
func (_e *MockIFileService_Expecter) Save(filename any, content any) *MockIFileService_Save_Call {
	return &MockIFileService_Save_Call{Call: _e.mock.On("Save", filename, content)}
}

func (_c *MockIFileService_Save_Call) Run(run func(filename string, content io.Reader)) *MockIFileService_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIFileService_Save_Call) Return(s string, err error) *MockIFileService_Save_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIFileService_Save_Call) RunAndReturn(run func(filename string, content io.Reader) (string, error)) *MockIFileService_Save_Call {
	_c.Call.Return(run)
	return _c
}
