// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIInfraRolePermissionRepo creates a new instance of MockIInfraRolePermissionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIInfraRolePermissionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIInfraRolePermissionRepo {
	mock := &MockIInfraRolePermissionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIInfraRolePermissionRepo is an autogenerated mock type for the IInfraRolePermissionRepo type
type MockIInfraRolePermissionRepo struct {
	mock.Mock
}

type MockIInfraRolePermissionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIInfraRolePermissionRepo) EXPECT() *MockIInfraRolePermissionRepo_Expecter {
	return &MockIInfraRolePermissionRepo_Expecter{mock: &_m.Mock}
}

// GetPermissionsByUser provides a mock function for the type MockIInfraRolePermissionRepo
func (_mock *MockIInfraRolePermissionRepo) GetPermissionsByUser(ctx context.Context, userID int64) ([]domain.Permission, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionsByUser")
	}

	var r0 []domain.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Permission, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []domain.Permission); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInfraRolePermissionRepo_GetPermissionsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionsByUser'
type MockIInfraRolePermissionRepo_GetPermissionsByUser_Call struct {
	*mock.Call
}

// GetPermissionsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockIInfraRolePermissionRepo_Expecter) GetPermissionsByUser(ctx any, userID any) *MockIInfraRolePermissionRepo_GetPermissionsByUser_Call {
	return &MockIInfraRolePermissionRepo_GetPermissionsByUser_Call{Call: _e.mock.On("GetPermissionsByUser", ctx, userID)}
}

func (_c *MockIInfraRolePermissionRepo_GetPermissionsByUser_Call) Run(run func(ctx context.Context, userID int64)) *MockIInfraRolePermissionRepo_GetPermissionsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIInfraRolePermissionRepo_GetPermissionsByUser_Call) Return(permissions []domain.Permission, err error) *MockIInfraRolePermissionRepo_GetPermissionsByUser_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *MockIInfraRolePermissionRepo_GetPermissionsByUser_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]domain.Permission, error)) *MockIInfraRolePermissionRepo_GetPermissionsByUser_Call {
	_c.Call.Return(run)
	return _c
}
