// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIJWTService creates a new instance of MockIJWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIJWTService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIJWTService {
	mock := &MockIJWTService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIJWTService is an autogenerated mock type for the IJWTService type
type MockIJWTService struct {
	mock.Mock
}

type MockIJWTService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIJWTService) EXPECT() *MockIJWTService_Expecter {
	return &MockIJWTService_Expecter{mock: &_m.Mock}
}

// IssueJWT provides a mock function for the type MockIJWTService
func (_mock *MockIJWTService) IssueJWT(userID int64, secret []byte) (string, error) {
	ret := _mock.Called(userID, secret)

	if len(ret) == 0 {
		panic("no return value specified for IssueJWT")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, []byte) (string, error)); ok {
		return returnFunc(userID, secret)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, []byte) string); ok {
		r0 = returnFunc(userID, secret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, []byte) error); ok {
		r1 = returnFunc(userID, secret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJWTService_IssueJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueJWT'
type MockIJWTService_IssueJWT_Call struct {
	*mock.Call
}

// IssueJWT is a helper method to define mock.On call
//   - userID int64
//   - secret []byte
func (_e *MockIJWTService_Expecter) IssueJWT(userID interface{}, secret interface{}) *MockIJWTService_IssueJWT_Call {
	return &MockIJWTService_IssueJWT_Call{Call: _e.mock.On("IssueJWT", userID, secret)}
}

func (_c *MockIJWTService_IssueJWT_Call) Run(run func(userID int64, secret []byte)) *MockIJWTService_IssueJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIJWTService_IssueJWT_Call) Return(s string, err error) *MockIJWTService_IssueJWT_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIJWTService_IssueJWT_Call) RunAndReturn(run func(userID int64, secret []byte) (string, error)) *MockIJWTService_IssueJWT_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockIJWTService
func (_mock *MockIJWTService) Verify(token string) (domain.UserClaims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 domain.UserClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (domain.UserClaims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.UserClaims); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(domain.UserClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJWTService_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockIJWTService_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - token string
func (_e *MockIJWTService_Expecter) Verify(token interface{}) *MockIJWTService_Verify_Call {
	return &MockIJWTService_Verify_Call{Call: _e.mock.On("Verify", token)}
}

func (_c *MockIJWTService_Verify_Call) Run(run func(token string)) *MockIJWTService_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIJWTService_Verify_Call) Return(userClaims domain.UserClaims, err error) *MockIJWTService_Verify_Call {
	_c.Call.Return(userClaims, err)
	return _c
}

func (_c *MockIJWTService_Verify_Call) RunAndReturn(run func(token string) (domain.UserClaims, error)) *MockIJWTService_Verify_Call {
	_c.Call.Return(run)
	return _c
}
