// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIJWTService creates a new instance of MockIJWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIJWTService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIJWTService {
	mock := &MockIJWTService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIJWTService is an autogenerated mock type for the IJWTService type
type MockIJWTService struct {
	mock.Mock
}

type MockIJWTService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIJWTService) EXPECT() *MockIJWTService_Expecter {
	return &MockIJWTService_Expecter{mock: &_m.Mock}
}

// IssueJWT provides a mock function for the type MockIJWTService
func (_mock *MockIJWTService) IssueJWT(ctx context.Context, userID int64, secret []byte) (string, error) {
	ret := _mock.Called(ctx, userID, secret)

	if len(ret) == 0 {
		panic("no return value specified for IssueJWT")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []byte) (string, error)); ok {
		return returnFunc(ctx, userID, secret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []byte) string); ok {
		r0 = returnFunc(ctx, userID, secret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, []byte) error); ok {
		r1 = returnFunc(ctx, userID, secret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJWTService_IssueJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueJWT'
type MockIJWTService_IssueJWT_Call struct {
	*mock.Call
}

// IssueJWT is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - secret []byte
func (_e *MockIJWTService_Expecter) IssueJWT(ctx any, userID any, secret any) *MockIJWTService_IssueJWT_Call {
	return &MockIJWTService_IssueJWT_Call{Call: _e.mock.On("IssueJWT", ctx, userID, secret)}
}

func (_c *MockIJWTService_IssueJWT_Call) Run(run func(ctx context.Context, userID int64, secret []byte)) *MockIJWTService_IssueJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIJWTService_IssueJWT_Call) Return(s string, err error) *MockIJWTService_IssueJWT_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIJWTService_IssueJWT_Call) RunAndReturn(run func(ctx context.Context, userID int64, secret []byte) (string, error)) *MockIJWTService_IssueJWT_Call {
	_c.Call.Return(run)
	return _c
}

// IssueRefreshToken provides a mock function for the type MockIJWTService
func (_mock *MockIJWTService) IssueRefreshToken(ctx context.Context, userID int64, secret []byte) (string, error) {
	ret := _mock.Called(ctx, userID, secret)

	if len(ret) == 0 {
		panic("no return value specified for IssueRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []byte) (string, error)); ok {
		return returnFunc(ctx, userID, secret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []byte) string); ok {
		r0 = returnFunc(ctx, userID, secret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, []byte) error); ok {
		r1 = returnFunc(ctx, userID, secret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJWTService_IssueRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueRefreshToken'
type MockIJWTService_IssueRefreshToken_Call struct {
	*mock.Call
}

// IssueRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - secret []byte
func (_e *MockIJWTService_Expecter) IssueRefreshToken(ctx any, userID any, secret any) *MockIJWTService_IssueRefreshToken_Call {
	return &MockIJWTService_IssueRefreshToken_Call{Call: _e.mock.On("IssueRefreshToken", ctx, userID, secret)}
}

func (_c *MockIJWTService_IssueRefreshToken_Call) Run(run func(ctx context.Context, userID int64, secret []byte)) *MockIJWTService_IssueRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIJWTService_IssueRefreshToken_Call) Return(s string, err error) *MockIJWTService_IssueRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIJWTService_IssueRefreshToken_Call) RunAndReturn(run func(ctx context.Context, userID int64, secret []byte) (string, error)) *MockIJWTService_IssueRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockIJWTService
func (_mock *MockIJWTService) Verify(token string) (domain.UserClaims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 domain.UserClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (domain.UserClaims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.UserClaims); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(domain.UserClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJWTService_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockIJWTService_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - token string
func (_e *MockIJWTService_Expecter) Verify(token any) *MockIJWTService_Verify_Call {
	return &MockIJWTService_Verify_Call{Call: _e.mock.On("Verify", token)}
}

func (_c *MockIJWTService_Verify_Call) Run(run func(token string)) *MockIJWTService_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIJWTService_Verify_Call) Return(userClaims domain.UserClaims, err error) *MockIJWTService_Verify_Call {
	_c.Call.Return(userClaims, err)
	return _c
}

func (_c *MockIJWTService_Verify_Call) RunAndReturn(run func(token string) (domain.UserClaims, error)) *MockIJWTService_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyRefreshToken provides a mock function for the type MockIJWTService
func (_mock *MockIJWTService) VerifyRefreshToken(ctx context.Context, token string) (domain.RefreshTokenClaims, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyRefreshToken")
	}

	var r0 domain.RefreshTokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.RefreshTokenClaims, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.RefreshTokenClaims); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(domain.RefreshTokenClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJWTService_VerifyRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyRefreshToken'
type MockIJWTService_VerifyRefreshToken_Call struct {
	*mock.Call
}

// VerifyRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockIJWTService_Expecter) VerifyRefreshToken(ctx any, token any) *MockIJWTService_VerifyRefreshToken_Call {
	return &MockIJWTService_VerifyRefreshToken_Call{Call: _e.mock.On("VerifyRefreshToken", ctx, token)}
}

func (_c *MockIJWTService_VerifyRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockIJWTService_VerifyRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIJWTService_VerifyRefreshToken_Call) Return(refreshTokenClaims domain.RefreshTokenClaims, err error) *MockIJWTService_VerifyRefreshToken_Call {
	_c.Call.Return(refreshTokenClaims, err)
	return _c
}

func (_c *MockIJWTService_VerifyRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) (domain.RefreshTokenClaims, error)) *MockIJWTService_VerifyRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
