// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIPasswordChecker creates a new instance of MockIPasswordChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPasswordChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPasswordChecker {
	mock := &MockIPasswordChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPasswordChecker is an autogenerated mock type for the IPasswordChecker type
type MockIPasswordChecker struct {
	mock.Mock
}

type MockIPasswordChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPasswordChecker) EXPECT() *MockIPasswordChecker_Expecter {
	return &MockIPasswordChecker_Expecter{mock: &_m.Mock}
}

// CheckPassword provides a mock function for the type MockIPasswordChecker
func (_mock *MockIPasswordChecker) CheckPassword(password string, hash string) (bool, error) {
	ret := _mock.Called(password, hash)

	if len(ret) == 0 {
		panic("no return value specified for CheckPassword")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(password, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(password, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(password, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPasswordChecker_CheckPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPassword'
type MockIPasswordChecker_CheckPassword_Call struct {
	*mock.Call
}

// CheckPassword is a helper method to define mock.On call
//   - password string
//   - hash string
func (_e *MockIPasswordChecker_Expecter) CheckPassword(password interface{}, hash interface{}) *MockIPasswordChecker_CheckPassword_Call {
	return &MockIPasswordChecker_CheckPassword_Call{Call: _e.mock.On("CheckPassword", password, hash)}
}

func (_c *MockIPasswordChecker_CheckPassword_Call) Run(run func(password string, hash string)) *MockIPasswordChecker_CheckPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPasswordChecker_CheckPassword_Call) Return(b bool, err error) *MockIPasswordChecker_CheckPassword_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIPasswordChecker_CheckPassword_Call) RunAndReturn(run func(password string, hash string) (bool, error)) *MockIPasswordChecker_CheckPassword_Call {
	_c.Call.Return(run)
	return _c
}

// HashPassword provides a mock function for the type MockIPasswordChecker
func (_mock *MockIPasswordChecker) HashPassword(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPasswordChecker_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockIPasswordChecker_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *MockIPasswordChecker_Expecter) HashPassword(password interface{}) *MockIPasswordChecker_HashPassword_Call {
	return &MockIPasswordChecker_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *MockIPasswordChecker_HashPassword_Call) Run(run func(password string)) *MockIPasswordChecker_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPasswordChecker_HashPassword_Call) Return(s string, err error) *MockIPasswordChecker_HashPassword_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIPasswordChecker_HashPassword_Call) RunAndReturn(run func(password string) (string, error)) *MockIPasswordChecker_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}
