// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIStorageClient creates a new instance of MockIStorageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStorageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStorageClient {
	mock := &MockIStorageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIStorageClient is an autogenerated mock type for the IStorageClient type
type MockIStorageClient struct {
	mock.Mock
}

type MockIStorageClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStorageClient) EXPECT() *MockIStorageClient_Expecter {
	return &MockIStorageClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockIStorageClient
func (_mock *MockIStorageClient) Get() *s3.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *s3.Client
	if returnFunc, ok := ret.Get(0).(func() *s3.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.Client)
		}
	}
	return r0
}

// MockIStorageClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIStorageClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockIStorageClient_Expecter) Get() *MockIStorageClient_Get_Call {
	return &MockIStorageClient_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockIStorageClient_Get_Call) Run(run func()) *MockIStorageClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIStorageClient_Get_Call) Return(client *s3.Client) *MockIStorageClient_Get_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockIStorageClient_Get_Call) RunAndReturn(run func() *s3.Client) *MockIStorageClient_Get_Call {
	_c.Call.Return(run)
	return _c
}
