// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIUserRepository creates a new instance of MockIUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserRepository {
	mock := &MockIUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUserRepository is an autogenerated mock type for the IUserRepository type
type MockIUserRepository struct {
	mock.Mock
}

type MockIUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserRepository) EXPECT() *MockIUserRepository_Expecter {
	return &MockIUserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) CreateUser(ctx context.Context, newUser domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, newUser)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, newUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, newUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, newUser)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - newUser domain.User
func (_e *MockIUserRepository_Expecter) CreateUser(ctx any, newUser any) *MockIUserRepository_CreateUser_Call {
	return &MockIUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, newUser)}
}

func (_c *MockIUserRepository_CreateUser_Call) Run(run func(ctx context.Context, newUser domain.User)) *MockIUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_CreateUser_Call) Return(user *domain.User, err error) *MockIUserRepository_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, newUser domain.User) (*domain.User, error)) *MockIUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserWithRole provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) CreateUserWithRole(ctx context.Context, newUser domain.User, role string) (*domain.User, error) {
	ret := _mock.Called(ctx, newUser, role)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserWithRole")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User, string) (*domain.User, error)); ok {
		return returnFunc(ctx, newUser, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User, string) *domain.User); ok {
		r0 = returnFunc(ctx, newUser, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User, string) error); ok {
		r1 = returnFunc(ctx, newUser, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_CreateUserWithRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserWithRole'
type MockIUserRepository_CreateUserWithRole_Call struct {
	*mock.Call
}

// CreateUserWithRole is a helper method to define mock.On call
//   - ctx context.Context
//   - newUser domain.User
//   - role string
func (_e *MockIUserRepository_Expecter) CreateUserWithRole(ctx any, newUser any, role any) *MockIUserRepository_CreateUserWithRole_Call {
	return &MockIUserRepository_CreateUserWithRole_Call{Call: _e.mock.On("CreateUserWithRole", ctx, newUser, role)}
}

func (_c *MockIUserRepository_CreateUserWithRole_Call) Run(run func(ctx context.Context, newUser domain.User, role string)) *MockIUserRepository_CreateUserWithRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIUserRepository_CreateUserWithRole_Call) Return(user *domain.User, err error) *MockIUserRepository_CreateUserWithRole_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_CreateUserWithRole_Call) RunAndReturn(run func(ctx context.Context, newUser domain.User, role string) (*domain.User, error)) *MockIUserRepository_CreateUserWithRole_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) Delete(ctx context.Context, id int64) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIUserRepository_Expecter) Delete(ctx any, id any) *MockIUserRepository_Delete_Call {
	return &MockIUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIUserRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockIUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_Delete_Call) Return(user *domain.User, err error) *MockIUserRepository_Delete_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.User, error)) *MockIUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUserByParam provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) FetchUserByParam(ctx context.Context, param domain.FetchUserParam) (*domain.User, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserByParam")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FetchUserParam) (*domain.User, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FetchUserParam) *domain.User); ok {
		r0 = returnFunc(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FetchUserParam) error); ok {
		r1 = returnFunc(ctx, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_FetchUserByParam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUserByParam'
type MockIUserRepository_FetchUserByParam_Call struct {
	*mock.Call
}

// FetchUserByParam is a helper method to define mock.On call
//   - ctx context.Context
//   - param domain.FetchUserParam
func (_e *MockIUserRepository_Expecter) FetchUserByParam(ctx any, param any) *MockIUserRepository_FetchUserByParam_Call {
	return &MockIUserRepository_FetchUserByParam_Call{Call: _e.mock.On("FetchUserByParam", ctx, param)}
}

func (_c *MockIUserRepository_FetchUserByParam_Call) Run(run func(ctx context.Context, param domain.FetchUserParam)) *MockIUserRepository_FetchUserByParam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FetchUserParam
		if args[1] != nil {
			arg1 = args[1].(domain.FetchUserParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_FetchUserByParam_Call) Return(user *domain.User, err error) *MockIUserRepository_FetchUserByParam_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_FetchUserByParam_Call) RunAndReturn(run func(ctx context.Context, param domain.FetchUserParam) (*domain.User, error)) *MockIUserRepository_FetchUserByParam_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) FindAll(ctx context.Context, param domain.FindAllUsersParam) ([]domain.User, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FindAllUsersParam) ([]domain.User, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FindAllUsersParam) []domain.User); ok {
		r0 = returnFunc(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FindAllUsersParam) error); ok {
		r1 = returnFunc(ctx, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockIUserRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - param domain.FindAllUsersParam
func (_e *MockIUserRepository_Expecter) FindAll(ctx any, param any) *MockIUserRepository_FindAll_Call {
	return &MockIUserRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, param)}
}

func (_c *MockIUserRepository_FindAll_Call) Run(run func(ctx context.Context, param domain.FindAllUsersParam)) *MockIUserRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FindAllUsersParam
		if args[1] != nil {
			arg1 = args[1].(domain.FindAllUsersParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_FindAll_Call) Return(users []domain.User, err error) *MockIUserRepository_FindAll_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockIUserRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, param domain.FindAllUsersParam) ([]domain.User, error)) *MockIUserRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) Update(ctx context.Context, id int64, param domain.UpdateUserParam) (*domain.User, error) {
	ret := _mock.Called(ctx, id, param)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, domain.UpdateUserParam) (*domain.User, error)); ok {
		return returnFunc(ctx, id, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, domain.UpdateUserParam) *domain.User); ok {
		r0 = returnFunc(ctx, id, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, domain.UpdateUserParam) error); ok {
		r1 = returnFunc(ctx, id, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - param domain.UpdateUserParam
func (_e *MockIUserRepository_Expecter) Update(ctx any, id any, param any) *MockIUserRepository_Update_Call {
	return &MockIUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, param)}
}

func (_c *MockIUserRepository_Update_Call) Run(run func(ctx context.Context, id int64, param domain.UpdateUserParam)) *MockIUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 domain.UpdateUserParam
		if args[2] != nil {
			arg2 = args[2].(domain.UpdateUserParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIUserRepository_Update_Call) Return(user *domain.User, err error) *MockIUserRepository_Update_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id int64, param domain.UpdateUserParam) (*domain.User, error)) *MockIUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
