// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIUserService creates a new instance of MockIUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserService {
	mock := &MockIUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUserService is an autogenerated mock type for the IUserService type
type MockIUserService struct {
	mock.Mock
}

type MockIUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserService) EXPECT() *MockIUserService_Expecter {
	return &MockIUserService_Expecter{mock: &_m.Mock}
}

// AuthenticateUser provides a mock function for the type MockIUserService
func (_mock *MockIUserService) AuthenticateUser(ctx context.Context, username string, password string) (*domain.User, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_AuthenticateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateUser'
type MockIUserService_AuthenticateUser_Call struct {
	*mock.Call
}

// AuthenticateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockIUserService_Expecter) AuthenticateUser(ctx interface{}, username interface{}, password interface{}) *MockIUserService_AuthenticateUser_Call {
	return &MockIUserService_AuthenticateUser_Call{Call: _e.mock.On("AuthenticateUser", ctx, username, password)}
}

func (_c *MockIUserService_AuthenticateUser_Call) Run(run func(ctx context.Context, username string, password string)) *MockIUserService_AuthenticateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIUserService_AuthenticateUser_Call) Return(user *domain.User, err error) *MockIUserService_AuthenticateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserService_AuthenticateUser_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (*domain.User, error)) *MockIUserService_AuthenticateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockIUserService
func (_mock *MockIUserService) CreateUser(ctx context.Context, user domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockIUserService_Expecter) CreateUser(ctx interface{}, user interface{}) *MockIUserService_CreateUser_Call {
	return &MockIUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockIUserService_CreateUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockIUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserService_CreateUser_Call) Return(user1 *domain.User, err error) *MockIUserService_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockIUserService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user domain.User) (*domain.User, error)) *MockIUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockIUserService
func (_mock *MockIUserService) FindAll(ctx context.Context, param domain.FindAllUsersParam) ([]domain.User, *domain.FindAllUsersParam, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.User
	var r1 *domain.FindAllUsersParam
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FindAllUsersParam) ([]domain.User, *domain.FindAllUsersParam, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FindAllUsersParam) []domain.User); ok {
		r0 = returnFunc(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FindAllUsersParam) *domain.FindAllUsersParam); ok {
		r1 = returnFunc(ctx, param)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.FindAllUsersParam)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.FindAllUsersParam) error); ok {
		r2 = returnFunc(ctx, param)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIUserService_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockIUserService_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - param domain.FindAllUsersParam
func (_e *MockIUserService_Expecter) FindAll(ctx interface{}, param interface{}) *MockIUserService_FindAll_Call {
	return &MockIUserService_FindAll_Call{Call: _e.mock.On("FindAll", ctx, param)}
}

func (_c *MockIUserService_FindAll_Call) Run(run func(ctx context.Context, param domain.FindAllUsersParam)) *MockIUserService_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FindAllUsersParam
		if args[1] != nil {
			arg1 = args[1].(domain.FindAllUsersParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserService_FindAll_Call) Return(users []domain.User, findAllUsersParam *domain.FindAllUsersParam, err error) *MockIUserService_FindAll_Call {
	_c.Call.Return(users, findAllUsersParam, err)
	return _c
}

func (_c *MockIUserService_FindAll_Call) RunAndReturn(run func(ctx context.Context, param domain.FindAllUsersParam) ([]domain.User, *domain.FindAllUsersParam, error)) *MockIUserService_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockIUserService
func (_mock *MockIUserService) GetUserByID(ctx context.Context, id int64) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockIUserService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIUserService_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockIUserService_GetUserByID_Call {
	return &MockIUserService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockIUserService_GetUserByID_Call) Run(run func(ctx context.Context, id int64)) *MockIUserService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserService_GetUserByID_Call) Return(user *domain.User, err error) *MockIUserService_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserService_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.User, error)) *MockIUserService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIUserService
func (_mock *MockIUserService) Update(ctx context.Context, id int64, update *domain.UpdateUserParam) (*domain.User, error) {
	ret := _mock.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *domain.UpdateUserParam) (*domain.User, error)); ok {
		return returnFunc(ctx, id, update)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *domain.UpdateUserParam) *domain.User); ok {
		r0 = returnFunc(ctx, id, update)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *domain.UpdateUserParam) error); ok {
		r1 = returnFunc(ctx, id, update)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIUserService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - update *domain.UpdateUserParam
func (_e *MockIUserService_Expecter) Update(ctx interface{}, id interface{}, update interface{}) *MockIUserService_Update_Call {
	return &MockIUserService_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *MockIUserService_Update_Call) Run(run func(ctx context.Context, id int64, update *domain.UpdateUserParam)) *MockIUserService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *domain.UpdateUserParam
		if args[2] != nil {
			arg2 = args[2].(*domain.UpdateUserParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIUserService_Update_Call) Return(user *domain.User, err error) *MockIUserService_Update_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserService_Update_Call) RunAndReturn(run func(ctx context.Context, id int64, update *domain.UpdateUserParam) (*domain.User, error)) *MockIUserService_Update_Call {
	_c.Call.Return(run)
	return _c
}
