services:
  backendpostgres:
    image: registry.hub.docker.com/pgvector/pgvector:pg18-trixie
    container_name: pg18-uwarag
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_ROOT_PASSWORD: password
    # env_file:
    #   - .env
    ports:
      - "${EXPOSEPORT:-5435}:5432"
    volumes:
      - data-volume-uwarag:/var/lib/postgresql

volumes:
  data-volume-uwarag:
    driver: local
