// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileRepository creates a new instance of MockFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileRepository {
	mock := &MockFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileRepository is an autogenerated mock type for the FileRepository type
type MockFileRepository struct {
	mock.Mock
}

type MockFileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileRepository) EXPECT() *MockFileRepository_Expecter {
	return &MockFileRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) Delete(ctx context.Context, id uuid.UUID) (*domain.File, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.File, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.File); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFileRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFileRepository_Expecter) Delete(ctx any, id any) *MockFileRepository_Delete_Call {
	return &MockFileRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockFileRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFileRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_Delete_Call) Return(file *domain.File, err error) *MockFileRepository_Delete_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.File, error)) *MockFileRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) FindAll(ctx context.Context, param *domain.FindAllFilesParam) ([]domain.File, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.FindAllFilesParam) ([]domain.File, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.FindAllFilesParam) []domain.File); ok {
		r0 = returnFunc(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.FindAllFilesParam) error); ok {
		r1 = returnFunc(ctx, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockFileRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - param *domain.FindAllFilesParam
func (_e *MockFileRepository_Expecter) FindAll(ctx any, param any) *MockFileRepository_FindAll_Call {
	return &MockFileRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, param)}
}

func (_c *MockFileRepository_FindAll_Call) Run(run func(ctx context.Context, param *domain.FindAllFilesParam)) *MockFileRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.FindAllFilesParam
		if args[1] != nil {
			arg1 = args[1].(*domain.FindAllFilesParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_FindAll_Call) Return(files []domain.File, err error) *MockFileRepository_FindAll_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, param *domain.FindAllFilesParam) ([]domain.File, error)) *MockFileRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) Get(ctx context.Context, fileID uuid.UUID) (*domain.File, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.File, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.File); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockFileRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID uuid.UUID
func (_e *MockFileRepository_Expecter) Get(ctx any, fileID any) *MockFileRepository_Get_Call {
	return &MockFileRepository_Get_Call{Call: _e.mock.On("Get", ctx, fileID)}
}

func (_c *MockFileRepository_Get_Call) Run(run func(ctx context.Context, fileID uuid.UUID)) *MockFileRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_Get_Call) Return(file *domain.File, err error) *MockFileRepository_Get_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_Get_Call) RunAndReturn(run func(ctx context.Context, fileID uuid.UUID) (*domain.File, error)) *MockFileRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) Insert(ctx context.Context, newFile domain.File) (*domain.File, error) {
	ret := _mock.Called(ctx, newFile)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.File) (*domain.File, error)); ok {
		return returnFunc(ctx, newFile)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.File) *domain.File); ok {
		r0 = returnFunc(ctx, newFile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.File) error); ok {
		r1 = returnFunc(ctx, newFile)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockFileRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - newFile domain.File
func (_e *MockFileRepository_Expecter) Insert(ctx any, newFile any) *MockFileRepository_Insert_Call {
	return &MockFileRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, newFile)}
}

func (_c *MockFileRepository_Insert_Call) Run(run func(ctx context.Context, newFile domain.File)) *MockFileRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.File
		if args[1] != nil {
			arg1 = args[1].(domain.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_Insert_Call) Return(file *domain.File, err error) *MockFileRepository_Insert_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, newFile domain.File) (*domain.File, error)) *MockFileRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) Update(ctx context.Context, id uuid.UUID, updateParam domain.UpdateFileParam) (*domain.File, error) {
	ret := _mock.Called(ctx, id, updateParam)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.UpdateFileParam) (*domain.File, error)); ok {
		return returnFunc(ctx, id, updateParam)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.UpdateFileParam) *domain.File); ok {
		r0 = returnFunc(ctx, id, updateParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.UpdateFileParam) error); ok {
		r1 = returnFunc(ctx, id, updateParam)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFileRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - updateParam domain.UpdateFileParam
func (_e *MockFileRepository_Expecter) Update(ctx any, id any, updateParam any) *MockFileRepository_Update_Call {
	return &MockFileRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, updateParam)}
}

func (_c *MockFileRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, updateParam domain.UpdateFileParam)) *MockFileRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.UpdateFileParam
		if args[2] != nil {
			arg2 = args[2].(domain.UpdateFileParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileRepository_Update_Call) Return(file *domain.File, err error) *MockFileRepository_Update_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, updateParam domain.UpdateFileParam) (*domain.File, error)) *MockFileRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
