// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorageClient creates a new instance of MockStorageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageClient {
	mock := &MockStorageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorageClient is an autogenerated mock type for the StorageClient type
type MockStorageClient struct {
	mock.Mock
}

type MockStorageClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageClient) EXPECT() *MockStorageClient_Expecter {
	return &MockStorageClient_Expecter{mock: &_m.Mock}
}

// GetPresignGetURL provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) GetPresignGetURL(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignGetURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_GetPresignGetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignGetURL'
type MockStorageClient_GetPresignGetURL_Call struct {
	*mock.Call
}

// GetPresignGetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageClient_Expecter) GetPresignGetURL(ctx any, key any) *MockStorageClient_GetPresignGetURL_Call {
	return &MockStorageClient_GetPresignGetURL_Call{Call: _e.mock.On("GetPresignGetURL", ctx, key)}
}

func (_c *MockStorageClient_GetPresignGetURL_Call) Run(run func(ctx context.Context, key string)) *MockStorageClient_GetPresignGetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageClient_GetPresignGetURL_Call) Return(s string, err error) *MockStorageClient_GetPresignGetURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorageClient_GetPresignGetURL_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockStorageClient_GetPresignGetURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresignPutURL provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) GetPresignPutURL(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignPutURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_GetPresignPutURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignPutURL'
type MockStorageClient_GetPresignPutURL_Call struct {
	*mock.Call
}

// GetPresignPutURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageClient_Expecter) GetPresignPutURL(ctx any, key any) *MockStorageClient_GetPresignPutURL_Call {
	return &MockStorageClient_GetPresignPutURL_Call{Call: _e.mock.On("GetPresignPutURL", ctx, key)}
}

func (_c *MockStorageClient_GetPresignPutURL_Call) Run(run func(ctx context.Context, key string)) *MockStorageClient_GetPresignPutURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageClient_GetPresignPutURL_Call) Return(s string, err error) *MockStorageClient_GetPresignPutURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorageClient_GetPresignPutURL_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockStorageClient_GetPresignPutURL_Call {
	_c.Call.Return(run)
	return _c
}
