openapi: "3.0.3"
info:
  title: Uwa Go Rag
  version: "1.0"
servers:
  - url: https://localhost:3000/api
  - url: http://localhost:3000/api
    description: unsecure
paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/refresh:
    post:
      tags:
        - Authentication
      summary: Refresh token endpoint
      description: Use other client such as postman/bruno. Scalar-api client (using docker container) might fail to send cookies
      # Apply the cookie security scheme to this specific endpoint
      security:
        - CookieAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users:
    post:
      tags:
        - User Management
      summary: Create a new user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SingleUserResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags:
        - User Management
      summary: Fetch users
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: username
          schema:
            type: string
          description: find username like
        - in: query
          name: size
          schema:
            type: integer
          description: limit the size (default 10)
        - in: query
          name: page
          schema:
            type: integer
          description: page number (default 1)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FetchUserResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/{id}:
    delete:
      tags:
        - User Management
      summary: Soft delete user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the user
          schema:
            type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "404":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    patch:
      tags:
        - User Management
      summary: Update user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the user
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserRequest"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "404":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/me:
    get:
      tags:
        - User Management
      summary: Fetch current user
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "404":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/{id}/password:
    post:
      tags:
        - User Management
      summary: Change current user password
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the user
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserPasswordRequest"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "404":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /roles:
    get:
      tags:
        - Role Management
      summary: Fetch roles
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: find name like
        - in: query
          name: size
          schema:
            type: integer
          description: limit the size (default 10)
        - in: query
          name: page
          schema:
            type: integer
          description: page number (default 1)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FetchRoleListResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /roles/{id}:
    get:
      tags:
        - Role Management
      summary: Fetch role by id
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/GetRoleResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auditlogs:
    get:
      tags:
        - Audit Logs
      summary: Fetch Audit Logs
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: resourceName
          schema:
            type: string
          description: find resource name like
        - in: query
          name: size
          schema:
            type: integer
          description: limit the size (default 10)
        - in: query
          name: page
          schema:
            type: integer
          description: page number (default 1)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FetchAuditLogResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /files:
    get:
      tags:
        - File Management
      summary: Fetch files
      description: Fetch files stored at the server
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: size
          schema:
            type: number
          description: limit the size (default 10)
        - in: query
          name: page
          schema:
            type: number
          description: page number (default 1)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FetchFilesResponse"

  /files/generate-presign-url:
    post:
      tags:
        - File Management
      summary: Generate Presigned URL
      description: Generate `PUT` method presigned object URL
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeneratePresignedURLRequest"
      responses:
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneratePresignedURLResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /files/{id}:
    patch:
      tags:
        - File Management
      summary: Update files
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateFilesRequest"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"

components:
  schemas:
    SuccessResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            message:
              type: string
    Pagination:
      type: object
      properties:
        page:
          type: integer
          example: 1
        size:
          type: integer
          example: 10
        total:
          type: integer
          example: 100
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            title:
              type: string
            message:
              type: string
    CreateUserRequest:
      type: object
      required:
        - username
        - password
        - roleID
      properties:
        username:
          type: string
          example: "newuser"
        password:
          type: string
          format: password
          example: "examplepassword"
        roleID:
          type: integer
          example: 12
    SingleUserResponse:
      type: "object"
      properties:
        data:
          type: "object"
          properties:
            id:
              type: "integer"
            username:
              type: "string"
            roleID:
              type: integer
            createdAt:
              type: "string"
              example: "2026-07-14T22:32:12.062975+07:00"
          required:
            - "id"
            - "username"
            - "roleID"
            - "createdAt"
    SingleUserEnrichedResponse:
      type: "object"
      properties:
        id:
          type: "integer"
        username:
          type: "string"
        roleID:
          type: integer
        createdAt:
          type: "string"
          example: "2026-07-14T22:32:12.062975+07:00"
        roleName:
          type: "string"
          example: "RoleName"
    FetchUserResponse:
      type: "object"
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/SingleUserEnrichedResponse"
        meta:
          type: "object"
          properties:
            usernamelike:
              type: "string"
              nullable: true
            pagination:
              $ref: "#/components/schemas/Pagination"
      required:
        - "data"
    GetRoleResponse:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        idname:
          type: "string"
          example: "1 - Superadmin"
    FetchRoleListResponse:
      type: "object"
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/GetRoleResponse"
        meta:
          type: "object"
          properties:
            namelike:
              type: "string"
              nullable: true
            pagination:
              $ref: "#/components/schemas/Pagination"
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: "user1"
        password:
          type: string
          format: password
          example: "mypassword123"
    LoginResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            token:
              type: string
    UpdateUserPasswordRequest:
      type: object
      properties:
        oldPassword:
          required: true
          type: string
        password:
          required: true
          type: string
    UpdateUserRequest:
      type: object
      properties:
        password:
          type: string
        roleID:
          type: integer
    FetchAuditLogResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                example: 101
              resourceName:
                type: string
                example: "users"
              actorID:
                type: integer
                nullable: true
                example: 1
              actorName:
                type: string
                example: "username"
              actorType:
                type: string
                example: "system"
              action:
                type: string
                example: "login"
              createdAt:
                type: string
                example: "2026-07-14T22:32:12.062975+07:00"
        meta:
          type: "object"
          properties:
            resourceNameLike:
              type: "string"
              nullable: true
            pagination:
              $ref: "#/components/schemas/Pagination"
    GeneratePresignedURLRequest:
      type: object
      properties:
        name:
          required: true
          type: string
          example: "my-file.jpg"
        sizeBytes:
          required: true
          type: number
          example: 1024
        mimeType:
          required: true
          type: string
          example: "image/png"
    GeneratePresignedURLResponse:
      type: object
      properties:
        fileID:
          type: string
          example: "uuid-string-here"
        presignURL:
          type: string
          example: "https://presign-url-to-s3"
    UpdateFilesRequest:
      type: object
      properties:
        status: string
        example: "completed"
    SingleFileResponse:
      type: object
      properties:
        id:
          type: string
          example: "uuid-string-here"
        userID:
          type: number
          example: 101
        originalName:
          type: string
          example: "file_name.jpg"
        mimeType:
          type: string
          example: "image/png"
        sizeBytes:
          type: integer
          example: 1024
        createdAt:
          type: string
          example: "20270101T00:00:00.000"
    FetchFilesResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/SingleFileResponse"
        meta:
          type: "object"
          properties:
            pagination:
              $ref: "#/components/schemas/Pagination"

  securitySchemes:
    BearerAuth: # Logical name for the scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # Optional, tells the client it's a JWT
    CookieAuth:
      type: apiKey
      in: cookie
      name: auth_session
