openapi: "3.0.3"
info:
  title: User API
  version: "1.0"
servers:
  - url: http://localhost:3000/api
paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/refresh:
    post:
      tags:
        - Authentication
      summary: Refresh token endpoint. Use other client such as postman/bruno. Scalar-api client (using docker container) might fail to send cookies.
      # Apply the cookie security scheme to this specific endpoint
      security:
        - CookieAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users:
    post:
      tags:
        - User Management
      summary: Create a new user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SingleUserResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    get:
      tags:
        - User Management
      summary: Fetch users
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: username
          schema:
            type: string
          description: find username like
        - in: query
          name: size
          schema:
            type: integer
          description: limit the size (default 10)
        - in: query
          name: page
          schema:
            type: integer
          description: page number (default 1)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FetchUserResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/{id}:
    delete:
      tags:
        - User Management
      summary: Soft delete user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the user
          schema:
            type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "404":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    patch:
      tags:
        - User Management
      summary: Update user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the user
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserRequest"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "404":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/{id}/password:
    post:
      tags:
        - User Management
      summary: Change current user password
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the user
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserPasswordRequest"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "404":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /roles:
    get:
      tags:
        - Role Management
      summary: Fetch roles
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: find name like
        - in: query
          name: size
          schema:
            type: integer
          description: limit the size (default 10)
        - in: query
          name: page
          schema:
            type: integer
          description: page number (default 1)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FetchRoleResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    SuccessResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            message:
              type: string
    Pagination:
      type: object
      properties:
        page:
          type: integer
          example: 1
        size:
          type: integer
          example: 10
        total:
          type: integer
          example: 100
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            title:
              type: string
            message:
              type: string
    CreateUserRequest:
      type: object
      required:
        - username
        - password
        - roleID
      properties:
        username:
          type: string
          example: "newuser"
        password:
          type: string
          format: password
          example: "examplepassword"
        roleID:
          type: integer
          example: 12
    SingleUserResponse:
      type: "object"
      properties:
        data:
          type: "object"
          properties:
            id:
              type: "integer"
            username:
              type: "string"
            roleID:
              type: integer
            createdAt:
              type: "string"
              example: "2026-07-14T22:32:12.062975+07:00"
          required:
            - "id"
            - "username"
            - "roleID"
            - "createdAt"
    FetchUserResponse:
      type: "object"
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/SingleUserResponse"
        meta:
          type: "object"
          properties:
            usernamelike:
              type: "string"
              nullable: true
            pagination:
              $ref: "#/components/schemas/Pagination"
      required:
        - "data"
    FetchRoleResponse:
      type: "object"
      properties:
        data:
          type: "array"
          items:
            type: "object"
            properties:
              id:
                type: "integer"
              name:
                type: "string"
        meta:
          type: "object"
          properties:
            namelike:
              type: "string"
              nullable: true
            pagination:
              $ref: "#/components/schemas/Pagination"
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: "user1"
        password:
          type: string
          format: password
          example: "mypassword123"
    LoginResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            token:
              type: string
    UpdateUserPasswordRequest:
      type: object
      properties:
        oldPassword:
          required: true
          type: string
        password:
          required: true
          type: string
    UpdateUserRequest:
      type: object
      properties:
        password:
          type: string
        roleID:
          type: integer

  securitySchemes:
    BearerAuth: # Logical name for the scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # Optional, tells the client it's a JWT
    CookieAuth:
      type: apiKey
      in: cookie
      name: auth_session
