# --- Required Metadata ---
sonar.projectKey=uwa-go-rag
sonar.projectName=UWA GO RAG
sonar.projectVersion=1.0

# --- Path to Source Code ---
# Generally '.' if your main.go or go.mod is in the root
sonar.sources=internal
sonar.exclusions=**/*_test.go,**/vendor/**,tmp/**,internal/mocks/**

# --- Test Configuration ---
# This tells SonarQube where to find your test files
sonar.tests=internal
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**,internal/mocks/**,web/public/**,web/templates/**

# --- Go Specific Reports ---
# These paths point to the files generated during your Gitea Action
sonar.go.tests.reportPath=report.json
sonar.go.coverage.reportPaths=coverage.out

# --- Encoding ---
sonar.sourceEncoding=UTF-8