// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileRepository creates a new instance of MockFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileRepository {
	mock := &MockFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileRepository is an autogenerated mock type for the FileRepository type
type MockFileRepository struct {
	mock.Mock
}

type MockFileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileRepository) EXPECT() *MockFileRepository_Expecter {
	return &MockFileRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) Get(ctx context.Context, fileID uuid.UUID) (*domain.File, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.File, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.File); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockFileRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID uuid.UUID
func (_e *MockFileRepository_Expecter) Get(ctx any, fileID any) *MockFileRepository_Get_Call {
	return &MockFileRepository_Get_Call{Call: _e.mock.On("Get", ctx, fileID)}
}

func (_c *MockFileRepository_Get_Call) Run(run func(ctx context.Context, fileID uuid.UUID)) *MockFileRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_Get_Call) Return(file *domain.File, err error) *MockFileRepository_Get_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_Get_Call) RunAndReturn(run func(ctx context.Context, fileID uuid.UUID) (*domain.File, error)) *MockFileRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) Insert(ctx context.Context, newFile domain.File) (*domain.File, error) {
	ret := _mock.Called(ctx, newFile)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.File) (*domain.File, error)); ok {
		return returnFunc(ctx, newFile)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.File) *domain.File); ok {
		r0 = returnFunc(ctx, newFile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.File) error); ok {
		r1 = returnFunc(ctx, newFile)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockFileRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - newFile domain.File
func (_e *MockFileRepository_Expecter) Insert(ctx any, newFile any) *MockFileRepository_Insert_Call {
	return &MockFileRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, newFile)}
}

func (_c *MockFileRepository_Insert_Call) Run(run func(ctx context.Context, newFile domain.File)) *MockFileRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.File
		if args[1] != nil {
			arg1 = args[1].(domain.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_Insert_Call) Return(file *domain.File, err error) *MockFileRepository_Insert_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, newFile domain.File) (*domain.File, error)) *MockFileRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}
