// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorageClient creates a new instance of MockStorageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageClient {
	mock := &MockStorageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorageClient is an autogenerated mock type for the StorageClient type
type MockStorageClient struct {
	mock.Mock
}

type MockStorageClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageClient) EXPECT() *MockStorageClient_Expecter {
	return &MockStorageClient_Expecter{mock: &_m.Mock}
}

// GetPresignURL provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) GetPresignURL(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_GetPresignURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignURL'
type MockStorageClient_GetPresignURL_Call struct {
	*mock.Call
}

// GetPresignURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageClient_Expecter) GetPresignURL(ctx any, key any) *MockStorageClient_GetPresignURL_Call {
	return &MockStorageClient_GetPresignURL_Call{Call: _e.mock.On("GetPresignURL", ctx, key)}
}

func (_c *MockStorageClient_GetPresignURL_Call) Run(run func(ctx context.Context, key string)) *MockStorageClient_GetPresignURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageClient_GetPresignURL_Call) Return(s string, err error) *MockStorageClient_GetPresignURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorageClient_GetPresignURL_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockStorageClient_GetPresignURL_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiles provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) ListFiles(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_ListFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiles'
type MockStorageClient_ListFiles_Call struct {
	*mock.Call
}

// ListFiles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorageClient_Expecter) ListFiles(ctx any) *MockStorageClient_ListFiles_Call {
	return &MockStorageClient_ListFiles_Call{Call: _e.mock.On("ListFiles", ctx)}
}

func (_c *MockStorageClient_ListFiles_Call) Run(run func(ctx context.Context)) *MockStorageClient_ListFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorageClient_ListFiles_Call) Return(strings []string, err error) *MockStorageClient_ListFiles_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockStorageClient_ListFiles_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockStorageClient_ListFiles_Call {
	_c.Call.Return(run)
	return _c
}
