// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateUser(ctx context.Context, user domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockUserService_Expecter) CreateUser(ctx any, user any) *MockUserService_CreateUser_Call {
	return &MockUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUserService_CreateUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_CreateUser_Call) Return(user1 *domain.User, err error) *MockUserService_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user domain.User) (*domain.User, error)) *MockUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserService
func (_mock *MockUserService) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUserService_Expecter) Delete(ctx any, id any) *MockUserService_Delete_Call {
	return &MockUserService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserService_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockUserService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Delete_Call) Return(err error) *MockUserService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockUserService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockUserService
func (_mock *MockUserService) FindAll(ctx context.Context, param domain.FindAllUsersParam) ([]domain.UserEnriched, *domain.FindAllUsersParam, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.UserEnriched
	var r1 *domain.FindAllUsersParam
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FindAllUsersParam) ([]domain.UserEnriched, *domain.FindAllUsersParam, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FindAllUsersParam) []domain.UserEnriched); ok {
		r0 = returnFunc(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserEnriched)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FindAllUsersParam) *domain.FindAllUsersParam); ok {
		r1 = returnFunc(ctx, param)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.FindAllUsersParam)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.FindAllUsersParam) error); ok {
		r2 = returnFunc(ctx, param)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserService_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockUserService_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - param domain.FindAllUsersParam
func (_e *MockUserService_Expecter) FindAll(ctx any, param any) *MockUserService_FindAll_Call {
	return &MockUserService_FindAll_Call{Call: _e.mock.On("FindAll", ctx, param)}
}

func (_c *MockUserService_FindAll_Call) Run(run func(ctx context.Context, param domain.FindAllUsersParam)) *MockUserService_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FindAllUsersParam
		if args[1] != nil {
			arg1 = args[1].(domain.FindAllUsersParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_FindAll_Call) Return(userEnricheds []domain.UserEnriched, findAllUsersParam *domain.FindAllUsersParam, err error) *MockUserService_FindAll_Call {
	_c.Call.Return(userEnricheds, findAllUsersParam, err)
	return _c
}

func (_c *MockUserService_FindAll_Call) RunAndReturn(run func(ctx context.Context, param domain.FindAllUsersParam) ([]domain.UserEnriched, *domain.FindAllUsersParam, error)) *MockUserService_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserByID(ctx context.Context, id int64) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUserService_Expecter) GetUserByID(ctx any, id any) *MockUserService_GetUserByID_Call {
	return &MockUserService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserService_GetUserByID_Call) Run(run func(ctx context.Context, id int64)) *MockUserService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetUserByID_Call) Return(user *domain.User, err error) *MockUserService_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.User, error)) *MockUserService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserService
func (_mock *MockUserService) Update(ctx context.Context, id int64, update *domain.UpdateUserParam) (*domain.User, error) {
	ret := _mock.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *domain.UpdateUserParam) (*domain.User, error)); ok {
		return returnFunc(ctx, id, update)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *domain.UpdateUserParam) *domain.User); ok {
		r0 = returnFunc(ctx, id, update)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *domain.UpdateUserParam) error); ok {
		r1 = returnFunc(ctx, id, update)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - update *domain.UpdateUserParam
func (_e *MockUserService_Expecter) Update(ctx any, id any, update any) *MockUserService_Update_Call {
	return &MockUserService_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *MockUserService_Update_Call) Run(run func(ctx context.Context, id int64, update *domain.UpdateUserParam)) *MockUserService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *domain.UpdateUserParam
		if args[2] != nil {
			arg2 = args[2].(*domain.UpdateUserParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_Update_Call) Return(user *domain.User, err error) *MockUserService_Update_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_Update_Call) RunAndReturn(run func(ctx context.Context, id int64, update *domain.UpdateUserParam) (*domain.User, error)) *MockUserService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type MockUserService
func (_mock *MockUserService) UpdatePassword(ctx context.Context, id int64, update *domain.UpdateUserParam) (*domain.User, error) {
	ret := _mock.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *domain.UpdateUserParam) (*domain.User, error)); ok {
		return returnFunc(ctx, id, update)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *domain.UpdateUserParam) *domain.User); ok {
		r0 = returnFunc(ctx, id, update)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *domain.UpdateUserParam) error); ok {
		r1 = returnFunc(ctx, id, update)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockUserService_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - update *domain.UpdateUserParam
func (_e *MockUserService_Expecter) UpdatePassword(ctx any, id any, update any) *MockUserService_UpdatePassword_Call {
	return &MockUserService_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, id, update)}
}

func (_c *MockUserService_UpdatePassword_Call) Run(run func(ctx context.Context, id int64, update *domain.UpdateUserParam)) *MockUserService_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *domain.UpdateUserParam
		if args[2] != nil {
			arg2 = args[2].(*domain.UpdateUserParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_UpdatePassword_Call) Return(user *domain.User, err error) *MockUserService_UpdatePassword_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_UpdatePassword_Call) RunAndReturn(run func(ctx context.Context, id int64, update *domain.UpdateUserParam) (*domain.User, error)) *MockUserService_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}
