// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) CreateUser(ctx context.Context, newUser domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, newUser)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, newUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, newUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, newUser)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - newUser domain.User
func (_e *MockUserRepository_Expecter) CreateUser(ctx any, newUser any) *MockUserRepository_CreateUser_Call {
	return &MockUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, newUser)}
}

func (_c *MockUserRepository_CreateUser_Call) Run(run func(ctx context.Context, newUser domain.User)) *MockUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) Return(user *domain.User, err error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, newUser domain.User) (*domain.User, error)) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserWithRole provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) CreateUserWithRole(ctx context.Context, newUser domain.User, role string) (*domain.User, error) {
	ret := _mock.Called(ctx, newUser, role)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserWithRole")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User, string) (*domain.User, error)); ok {
		return returnFunc(ctx, newUser, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User, string) *domain.User); ok {
		r0 = returnFunc(ctx, newUser, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User, string) error); ok {
		r1 = returnFunc(ctx, newUser, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_CreateUserWithRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserWithRole'
type MockUserRepository_CreateUserWithRole_Call struct {
	*mock.Call
}

// CreateUserWithRole is a helper method to define mock.On call
//   - ctx context.Context
//   - newUser domain.User
//   - role string
func (_e *MockUserRepository_Expecter) CreateUserWithRole(ctx any, newUser any, role any) *MockUserRepository_CreateUserWithRole_Call {
	return &MockUserRepository_CreateUserWithRole_Call{Call: _e.mock.On("CreateUserWithRole", ctx, newUser, role)}
}

func (_c *MockUserRepository_CreateUserWithRole_Call) Run(run func(ctx context.Context, newUser domain.User, role string)) *MockUserRepository_CreateUserWithRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_CreateUserWithRole_Call) Return(user *domain.User, err error) *MockUserRepository_CreateUserWithRole_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_CreateUserWithRole_Call) RunAndReturn(run func(ctx context.Context, newUser domain.User, role string) (*domain.User, error)) *MockUserRepository_CreateUserWithRole_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Delete(ctx context.Context, id int64) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUserRepository_Expecter) Delete(ctx any, id any) *MockUserRepository_Delete_Call {
	return &MockUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Delete_Call) Return(user *domain.User, err error) *MockUserRepository_Delete_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.User, error)) *MockUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUserByParam provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FetchUserByParam(ctx context.Context, param domain.FetchUserParam) (*domain.User, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserByParam")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FetchUserParam) (*domain.User, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FetchUserParam) *domain.User); ok {
		r0 = returnFunc(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FetchUserParam) error); ok {
		r1 = returnFunc(ctx, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FetchUserByParam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUserByParam'
type MockUserRepository_FetchUserByParam_Call struct {
	*mock.Call
}

// FetchUserByParam is a helper method to define mock.On call
//   - ctx context.Context
//   - param domain.FetchUserParam
func (_e *MockUserRepository_Expecter) FetchUserByParam(ctx any, param any) *MockUserRepository_FetchUserByParam_Call {
	return &MockUserRepository_FetchUserByParam_Call{Call: _e.mock.On("FetchUserByParam", ctx, param)}
}

func (_c *MockUserRepository_FetchUserByParam_Call) Run(run func(ctx context.Context, param domain.FetchUserParam)) *MockUserRepository_FetchUserByParam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FetchUserParam
		if args[1] != nil {
			arg1 = args[1].(domain.FetchUserParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FetchUserByParam_Call) Return(user *domain.User, err error) *MockUserRepository_FetchUserByParam_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FetchUserByParam_Call) RunAndReturn(run func(ctx context.Context, param domain.FetchUserParam) (*domain.User, error)) *MockUserRepository_FetchUserByParam_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindAll(ctx context.Context, param *domain.FindAllUsersParam) ([]domain.UserEnriched, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.UserEnriched
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.FindAllUsersParam) ([]domain.UserEnriched, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.FindAllUsersParam) []domain.UserEnriched); ok {
		r0 = returnFunc(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserEnriched)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.FindAllUsersParam) error); ok {
		r1 = returnFunc(ctx, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockUserRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - param *domain.FindAllUsersParam
func (_e *MockUserRepository_Expecter) FindAll(ctx any, param any) *MockUserRepository_FindAll_Call {
	return &MockUserRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, param)}
}

func (_c *MockUserRepository_FindAll_Call) Run(run func(ctx context.Context, param *domain.FindAllUsersParam)) *MockUserRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.FindAllUsersParam
		if args[1] != nil {
			arg1 = args[1].(*domain.FindAllUsersParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindAll_Call) Return(userEnricheds []domain.UserEnriched, err error) *MockUserRepository_FindAll_Call {
	_c.Call.Return(userEnricheds, err)
	return _c
}

func (_c *MockUserRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, param *domain.FindAllUsersParam) ([]domain.UserEnriched, error)) *MockUserRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Update(ctx context.Context, id int64, param domain.UpdateUserParam) (*domain.User, error) {
	ret := _mock.Called(ctx, id, param)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, domain.UpdateUserParam) (*domain.User, error)); ok {
		return returnFunc(ctx, id, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, domain.UpdateUserParam) *domain.User); ok {
		r0 = returnFunc(ctx, id, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, domain.UpdateUserParam) error); ok {
		r1 = returnFunc(ctx, id, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - param domain.UpdateUserParam
func (_e *MockUserRepository_Expecter) Update(ctx any, id any, param any) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, param)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(ctx context.Context, id int64, param domain.UpdateUserParam)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 domain.UpdateUserParam
		if args[2] != nil {
			arg2 = args[2].(domain.UpdateUserParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(user *domain.User, err error) *MockUserRepository_Update_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id int64, param domain.UpdateUserParam) (*domain.User, error)) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
