// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/audit"
	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRecorder creates a new instance of MockRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecorder {
	mock := &MockRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRecorder is an autogenerated mock type for the Recorder type
type MockRecorder struct {
	mock.Mock
}

type MockRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecorder) EXPECT() *MockRecorder_Expecter {
	return &MockRecorder_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function for the type MockRecorder
func (_mock *MockRecorder) FindAll(ctx context.Context, param audit.AuditLogFetchParam) ([]domain.AuditLog, *audit.AuditLogFetchParam, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.AuditLog
	var r1 *audit.AuditLogFetchParam
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, audit.AuditLogFetchParam) ([]domain.AuditLog, *audit.AuditLogFetchParam, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, audit.AuditLogFetchParam) []domain.AuditLog); ok {
		r0 = returnFunc(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AuditLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, audit.AuditLogFetchParam) *audit.AuditLogFetchParam); ok {
		r1 = returnFunc(ctx, param)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*audit.AuditLogFetchParam)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, audit.AuditLogFetchParam) error); ok {
		r2 = returnFunc(ctx, param)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRecorder_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRecorder_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - param audit.AuditLogFetchParam
func (_e *MockRecorder_Expecter) FindAll(ctx any, param any) *MockRecorder_FindAll_Call {
	return &MockRecorder_FindAll_Call{Call: _e.mock.On("FindAll", ctx, param)}
}

func (_c *MockRecorder_FindAll_Call) Run(run func(ctx context.Context, param audit.AuditLogFetchParam)) *MockRecorder_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 audit.AuditLogFetchParam
		if args[1] != nil {
			arg1 = args[1].(audit.AuditLogFetchParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRecorder_FindAll_Call) Return(auditLogs []domain.AuditLog, auditLogFetchParam *audit.AuditLogFetchParam, err error) *MockRecorder_FindAll_Call {
	_c.Call.Return(auditLogs, auditLogFetchParam, err)
	return _c
}

func (_c *MockRecorder_FindAll_Call) RunAndReturn(run func(ctx context.Context, param audit.AuditLogFetchParam) ([]domain.AuditLog, *audit.AuditLogFetchParam, error)) *MockRecorder_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// Record provides a mock function for the type MockRecorder
func (_mock *MockRecorder) Record(ctx context.Context, auditlog domain.AuditLog) error {
	ret := _mock.Called(ctx, auditlog)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AuditLog) error); ok {
		r0 = returnFunc(ctx, auditlog)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRecorder_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockRecorder_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - auditlog domain.AuditLog
func (_e *MockRecorder_Expecter) Record(ctx any, auditlog any) *MockRecorder_Record_Call {
	return &MockRecorder_Record_Call{Call: _e.mock.On("Record", ctx, auditlog)}
}

func (_c *MockRecorder_Record_Call) Run(run func(ctx context.Context, auditlog domain.AuditLog)) *MockRecorder_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AuditLog
		if args[1] != nil {
			arg1 = args[1].(domain.AuditLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRecorder_Record_Call) Return(err error) *MockRecorder_Record_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRecorder_Record_Call) RunAndReturn(run func(ctx context.Context, auditlog domain.AuditLog) error) *MockRecorder_Record_Call {
	_c.Call.Return(run)
	return _c
}
