// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function for the type MockRepository
func (_mock *MockRepository) FindAll(ctx context.Context, param *domain.AuditLogFetchParam) ([]domain.AuditLog, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.AuditLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditLogFetchParam) ([]domain.AuditLog, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditLogFetchParam) []domain.AuditLog); ok {
		r0 = returnFunc(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AuditLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuditLogFetchParam) error); ok {
		r1 = returnFunc(ctx, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - param *domain.AuditLogFetchParam
func (_e *MockRepository_Expecter) FindAll(ctx any, param any) *MockRepository_FindAll_Call {
	return &MockRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, param)}
}

func (_c *MockRepository_FindAll_Call) Run(run func(ctx context.Context, param *domain.AuditLogFetchParam)) *MockRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditLogFetchParam
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditLogFetchParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindAll_Call) Return(auditLogs []domain.AuditLog, err error) *MockRepository_FindAll_Call {
	_c.Call.Return(auditLogs, err)
	return _c
}

func (_c *MockRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, param *domain.AuditLogFetchParam) ([]domain.AuditLog, error)) *MockRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockRepository
func (_mock *MockRepository) Insert(ctx context.Context, auditlog domain.AuditLog) error {
	ret := _mock.Called(ctx, auditlog)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AuditLog) error); ok {
		r0 = returnFunc(ctx, auditlog)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - auditlog domain.AuditLog
func (_e *MockRepository_Expecter) Insert(ctx any, auditlog any) *MockRepository_Insert_Call {
	return &MockRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, auditlog)}
}

func (_c *MockRepository_Insert_Call) Run(run func(ctx context.Context, auditlog domain.AuditLog)) *MockRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AuditLog
		if args[1] != nil {
			arg1 = args[1].(domain.AuditLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Insert_Call) Return(err error) *MockRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, auditlog domain.AuditLog) error) *MockRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}
