// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/chat"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatService creates a new instance of MockChatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatService {
	mock := &MockChatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatService is an autogenerated mock type for the ChatService type
type MockChatService struct {
	mock.Mock
}

type MockChatService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatService) EXPECT() *MockChatService_Expecter {
	return &MockChatService_Expecter{mock: &_m.Mock}
}

// Chat provides a mock function for the type MockChatService
func (_mock *MockChatService) Chat(ctx context.Context, prompt string) (*chat.ChatResponse, error) {
	ret := _mock.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 *chat.ChatResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*chat.ChatResponse, error)); ok {
		return returnFunc(ctx, prompt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *chat.ChatResponse); ok {
		r0 = returnFunc(ctx, prompt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.ChatResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatService_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockChatService_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
func (_e *MockChatService_Expecter) Chat(ctx any, prompt any) *MockChatService_Chat_Call {
	return &MockChatService_Chat_Call{Call: _e.mock.On("Chat", ctx, prompt)}
}

func (_c *MockChatService_Chat_Call) Run(run func(ctx context.Context, prompt string)) *MockChatService_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatService_Chat_Call) Return(chatResponse *chat.ChatResponse, err error) *MockChatService_Chat_Call {
	_c.Call.Return(chatResponse, err)
	return _c
}

func (_c *MockChatService_Chat_Call) RunAndReturn(run func(ctx context.Context, prompt string) (*chat.ChatResponse, error)) *MockChatService_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// SendTextIntoEmbedding provides a mock function for the type MockChatService
func (_mock *MockChatService) SendTextIntoEmbedding(ctx context.Context, text string) error {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for SendTextIntoEmbedding")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatService_SendTextIntoEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTextIntoEmbedding'
type MockChatService_SendTextIntoEmbedding_Call struct {
	*mock.Call
}

// SendTextIntoEmbedding is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockChatService_Expecter) SendTextIntoEmbedding(ctx any, text any) *MockChatService_SendTextIntoEmbedding_Call {
	return &MockChatService_SendTextIntoEmbedding_Call{Call: _e.mock.On("SendTextIntoEmbedding", ctx, text)}
}

func (_c *MockChatService_SendTextIntoEmbedding_Call) Run(run func(ctx context.Context, text string)) *MockChatService_SendTextIntoEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatService_SendTextIntoEmbedding_Call) Return(err error) *MockChatService_SendTextIntoEmbedding_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatService_SendTextIntoEmbedding_Call) RunAndReturn(run func(ctx context.Context, text string) error) *MockChatService_SendTextIntoEmbedding_Call {
	_c.Call.Return(run)
	return _c
}
