// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/chat"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIChatService creates a new instance of MockIChatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIChatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIChatService {
	mock := &MockIChatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIChatService is an autogenerated mock type for the IChatService type
type MockIChatService struct {
	mock.Mock
}

type MockIChatService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIChatService) EXPECT() *MockIChatService_Expecter {
	return &MockIChatService_Expecter{mock: &_m.Mock}
}

// Chat provides a mock function for the type MockIChatService
func (_mock *MockIChatService) Chat(ctx context.Context, prompt string) (*chat.ChatResponse, error) {
	ret := _mock.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 *chat.ChatResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*chat.ChatResponse, error)); ok {
		return returnFunc(ctx, prompt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *chat.ChatResponse); ok {
		r0 = returnFunc(ctx, prompt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.ChatResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIChatService_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockIChatService_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
func (_e *MockIChatService_Expecter) Chat(ctx any, prompt any) *MockIChatService_Chat_Call {
	return &MockIChatService_Chat_Call{Call: _e.mock.On("Chat", ctx, prompt)}
}

func (_c *MockIChatService_Chat_Call) Run(run func(ctx context.Context, prompt string)) *MockIChatService_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIChatService_Chat_Call) Return(chatResponse *chat.ChatResponse, err error) *MockIChatService_Chat_Call {
	_c.Call.Return(chatResponse, err)
	return _c
}

func (_c *MockIChatService_Chat_Call) RunAndReturn(run func(ctx context.Context, prompt string) (*chat.ChatResponse, error)) *MockIChatService_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// DoSort provides a mock function for the type MockIChatService
func (_mock *MockIChatService) DoSort(ctx context.Context, words []string) ([]string, error) {
	ret := _mock.Called(ctx, words)

	if len(ret) == 0 {
		panic("no return value specified for DoSort")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return returnFunc(ctx, words)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = returnFunc(ctx, words)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, words)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIChatService_DoSort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoSort'
type MockIChatService_DoSort_Call struct {
	*mock.Call
}

// DoSort is a helper method to define mock.On call
//   - ctx context.Context
//   - words []string
func (_e *MockIChatService_Expecter) DoSort(ctx any, words any) *MockIChatService_DoSort_Call {
	return &MockIChatService_DoSort_Call{Call: _e.mock.On("DoSort", ctx, words)}
}

func (_c *MockIChatService_DoSort_Call) Run(run func(ctx context.Context, words []string)) *MockIChatService_DoSort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIChatService_DoSort_Call) Return(strings []string, err error) *MockIChatService_DoSort_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockIChatService_DoSort_Call) RunAndReturn(run func(ctx context.Context, words []string) ([]string, error)) *MockIChatService_DoSort_Call {
	_c.Call.Return(run)
	return _c
}

// SendPrompt provides a mock function for the type MockIChatService
func (_mock *MockIChatService) SendPrompt(ctx context.Context, prompt string) (string, error) {
	ret := _mock.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for SendPrompt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, prompt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, prompt)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIChatService_SendPrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPrompt'
type MockIChatService_SendPrompt_Call struct {
	*mock.Call
}

// SendPrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
func (_e *MockIChatService_Expecter) SendPrompt(ctx any, prompt any) *MockIChatService_SendPrompt_Call {
	return &MockIChatService_SendPrompt_Call{Call: _e.mock.On("SendPrompt", ctx, prompt)}
}

func (_c *MockIChatService_SendPrompt_Call) Run(run func(ctx context.Context, prompt string)) *MockIChatService_SendPrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIChatService_SendPrompt_Call) Return(s string, err error) *MockIChatService_SendPrompt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIChatService_SendPrompt_Call) RunAndReturn(run func(ctx context.Context, prompt string) (string, error)) *MockIChatService_SendPrompt_Call {
	_c.Call.Return(run)
	return _c
}

// SendSortJob provides a mock function for the type MockIChatService
func (_mock *MockIChatService) SendSortJob(ctx context.Context, words []string) error {
	ret := _mock.Called(ctx, words)

	if len(ret) == 0 {
		panic("no return value specified for SendSortJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, words)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIChatService_SendSortJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSortJob'
type MockIChatService_SendSortJob_Call struct {
	*mock.Call
}

// SendSortJob is a helper method to define mock.On call
//   - ctx context.Context
//   - words []string
func (_e *MockIChatService_Expecter) SendSortJob(ctx any, words any) *MockIChatService_SendSortJob_Call {
	return &MockIChatService_SendSortJob_Call{Call: _e.mock.On("SendSortJob", ctx, words)}
}

func (_c *MockIChatService_SendSortJob_Call) Run(run func(ctx context.Context, words []string)) *MockIChatService_SendSortJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIChatService_SendSortJob_Call) Return(err error) *MockIChatService_SendSortJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIChatService_SendSortJob_Call) RunAndReturn(run func(ctx context.Context, words []string) error) *MockIChatService_SendSortJob_Call {
	_c.Call.Return(run)
	return _c
}

// SendTextIntoEmbedding provides a mock function for the type MockIChatService
func (_mock *MockIChatService) SendTextIntoEmbedding(ctx context.Context, text string) error {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for SendTextIntoEmbedding")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIChatService_SendTextIntoEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTextIntoEmbedding'
type MockIChatService_SendTextIntoEmbedding_Call struct {
	*mock.Call
}

// SendTextIntoEmbedding is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockIChatService_Expecter) SendTextIntoEmbedding(ctx any, text any) *MockIChatService_SendTextIntoEmbedding_Call {
	return &MockIChatService_SendTextIntoEmbedding_Call{Call: _e.mock.On("SendTextIntoEmbedding", ctx, text)}
}

func (_c *MockIChatService_SendTextIntoEmbedding_Call) Run(run func(ctx context.Context, text string)) *MockIChatService_SendTextIntoEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIChatService_SendTextIntoEmbedding_Call) Return(err error) *MockIChatService_SendTextIntoEmbedding_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIChatService_SendTextIntoEmbedding_Call) RunAndReturn(run func(ctx context.Context, text string) error) *MockIChatService_SendTextIntoEmbedding_Call {
	_c.Call.Return(run)
	return _c
}
