// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLLMClient creates a new instance of MockLLMClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLMClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLMClient {
	mock := &MockLLMClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLLMClient is an autogenerated mock type for the LLMClient type
type MockLLMClient struct {
	mock.Mock
}

type MockLLMClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLMClient) EXPECT() *MockLLMClient_Expecter {
	return &MockLLMClient_Expecter{mock: &_m.Mock}
}

// SendContextPrompt provides a mock function for the type MockLLMClient
func (_mock *MockLLMClient) SendContextPrompt(ctx context.Context, contextText string, question string) (string, error) {
	ret := _mock.Called(ctx, contextText, question)

	if len(ret) == 0 {
		panic("no return value specified for SendContextPrompt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, contextText, question)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, contextText, question)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, contextText, question)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLLMClient_SendContextPrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendContextPrompt'
type MockLLMClient_SendContextPrompt_Call struct {
	*mock.Call
}

// SendContextPrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - contextText string
//   - question string
func (_e *MockLLMClient_Expecter) SendContextPrompt(ctx any, contextText any, question any) *MockLLMClient_SendContextPrompt_Call {
	return &MockLLMClient_SendContextPrompt_Call{Call: _e.mock.On("SendContextPrompt", ctx, contextText, question)}
}

func (_c *MockLLMClient_SendContextPrompt_Call) Run(run func(ctx context.Context, contextText string, question string)) *MockLLMClient_SendContextPrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLLMClient_SendContextPrompt_Call) Return(s string, err error) *MockLLMClient_SendContextPrompt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLLMClient_SendContextPrompt_Call) RunAndReturn(run func(ctx context.Context, contextText string, question string) (string, error)) *MockLLMClient_SendContextPrompt_Call {
	_c.Call.Return(run)
	return _c
}

// SendPrompt provides a mock function for the type MockLLMClient
func (_mock *MockLLMClient) SendPrompt(ctx context.Context, prompt string) (string, error) {
	ret := _mock.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for SendPrompt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, prompt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, prompt)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLLMClient_SendPrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPrompt'
type MockLLMClient_SendPrompt_Call struct {
	*mock.Call
}

// SendPrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
func (_e *MockLLMClient_Expecter) SendPrompt(ctx any, prompt any) *MockLLMClient_SendPrompt_Call {
	return &MockLLMClient_SendPrompt_Call{Call: _e.mock.On("SendPrompt", ctx, prompt)}
}

func (_c *MockLLMClient_SendPrompt_Call) Run(run func(ctx context.Context, prompt string)) *MockLLMClient_SendPrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLLMClient_SendPrompt_Call) Return(s string, err error) *MockLLMClient_SendPrompt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLLMClient_SendPrompt_Call) RunAndReturn(run func(ctx context.Context, prompt string) (string, error)) *MockLLMClient_SendPrompt_Call {
	_c.Call.Return(run)
	return _c
}
