// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRetrievalRepository creates a new instance of MockRetrievalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRetrievalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRetrievalRepository {
	mock := &MockRetrievalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRetrievalRepository is an autogenerated mock type for the RetrievalRepository type
type MockRetrievalRepository struct {
	mock.Mock
}

type MockRetrievalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRetrievalRepository) EXPECT() *MockRetrievalRepository_Expecter {
	return &MockRetrievalRepository_Expecter{mock: &_m.Mock}
}

// SearchSimilar provides a mock function for the type MockRetrievalRepository
func (_mock *MockRetrievalRepository) SearchSimilar(ctx context.Context, embedding []float32, limit int, threshold float64) ([]domain.Chunk, error) {
	ret := _mock.Called(ctx, embedding, limit, threshold)

	if len(ret) == 0 {
		panic("no return value specified for SearchSimilar")
	}

	var r0 []domain.Chunk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []float32, int, float64) ([]domain.Chunk, error)); ok {
		return returnFunc(ctx, embedding, limit, threshold)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []float32, int, float64) []domain.Chunk); ok {
		r0 = returnFunc(ctx, embedding, limit, threshold)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Chunk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []float32, int, float64) error); ok {
		r1 = returnFunc(ctx, embedding, limit, threshold)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRetrievalRepository_SearchSimilar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSimilar'
type MockRetrievalRepository_SearchSimilar_Call struct {
	*mock.Call
}

// SearchSimilar is a helper method to define mock.On call
//   - ctx context.Context
//   - embedding []float32
//   - limit int
//   - threshold float64
func (_e *MockRetrievalRepository_Expecter) SearchSimilar(ctx any, embedding any, limit any, threshold any) *MockRetrievalRepository_SearchSimilar_Call {
	return &MockRetrievalRepository_SearchSimilar_Call{Call: _e.mock.On("SearchSimilar", ctx, embedding, limit, threshold)}
}

func (_c *MockRetrievalRepository_SearchSimilar_Call) Run(run func(ctx context.Context, embedding []float32, limit int, threshold float64)) *MockRetrievalRepository_SearchSimilar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []float32
		if args[1] != nil {
			arg1 = args[1].([]float32)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRetrievalRepository_SearchSimilar_Call) Return(chunks []domain.Chunk, err error) *MockRetrievalRepository_SearchSimilar_Call {
	_c.Call.Return(chunks, err)
	return _c
}

func (_c *MockRetrievalRepository_SearchSimilar_Call) RunAndReturn(run func(ctx context.Context, embedding []float32, limit int, threshold float64) ([]domain.Chunk, error)) *MockRetrievalRepository_SearchSimilar_Call {
	_c.Call.Return(run)
	return _c
}
