// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUnansweredRecorder creates a new instance of MockUnansweredRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnansweredRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnansweredRecorder {
	mock := &MockUnansweredRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnansweredRecorder is an autogenerated mock type for the UnansweredRecorder type
type MockUnansweredRecorder struct {
	mock.Mock
}

type MockUnansweredRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnansweredRecorder) EXPECT() *MockUnansweredRecorder_Expecter {
	return &MockUnansweredRecorder_Expecter{mock: &_m.Mock}
}

// RecordUnanswered provides a mock function for the type MockUnansweredRecorder
func (_mock *MockUnansweredRecorder) RecordUnanswered(ctx context.Context, question string) error {
	ret := _mock.Called(ctx, question)

	if len(ret) == 0 {
		panic("no return value specified for RecordUnanswered")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, question)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnansweredRecorder_RecordUnanswered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordUnanswered'
type MockUnansweredRecorder_RecordUnanswered_Call struct {
	*mock.Call
}

// RecordUnanswered is a helper method to define mock.On call
//   - ctx context.Context
//   - question string
func (_e *MockUnansweredRecorder_Expecter) RecordUnanswered(ctx any, question any) *MockUnansweredRecorder_RecordUnanswered_Call {
	return &MockUnansweredRecorder_RecordUnanswered_Call{Call: _e.mock.On("RecordUnanswered", ctx, question)}
}

func (_c *MockUnansweredRecorder_RecordUnanswered_Call) Run(run func(ctx context.Context, question string)) *MockUnansweredRecorder_RecordUnanswered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUnansweredRecorder_RecordUnanswered_Call) Return(err error) *MockUnansweredRecorder_RecordUnanswered_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnansweredRecorder_RecordUnanswered_Call) RunAndReturn(run func(ctx context.Context, question string) error) *MockUnansweredRecorder_RecordUnanswered_Call {
	_c.Call.Return(run)
	return _c
}
