// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenizer creates a new instance of MockTokenizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenizer {
	mock := &MockTokenizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenizer is an autogenerated mock type for the Tokenizer type
type MockTokenizer struct {
	mock.Mock
}

type MockTokenizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenizer) EXPECT() *MockTokenizer_Expecter {
	return &MockTokenizer_Expecter{mock: &_m.Mock}
}

// CountTokens provides a mock function for the type MockTokenizer
func (_mock *MockTokenizer) CountTokens(text string) int {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for CountTokens")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(text)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockTokenizer_CountTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountTokens'
type MockTokenizer_CountTokens_Call struct {
	*mock.Call
}

// CountTokens is a helper method to define mock.On call
//   - text string
func (_e *MockTokenizer_Expecter) CountTokens(text any) *MockTokenizer_CountTokens_Call {
	return &MockTokenizer_CountTokens_Call{Call: _e.mock.On("CountTokens", text)}
}

func (_c *MockTokenizer_CountTokens_Call) Run(run func(text string)) *MockTokenizer_CountTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenizer_CountTokens_Call) Return(n int) *MockTokenizer_CountTokens_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockTokenizer_CountTokens_Call) RunAndReturn(run func(text string) int) *MockTokenizer_CountTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Decode provides a mock function for the type MockTokenizer
func (_mock *MockTokenizer) Decode(tokens []int) (string, error) {
	ret := _mock.Called(tokens)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int) (string, error)); ok {
		return returnFunc(tokens)
	}
	if returnFunc, ok := ret.Get(0).(func([]int) string); ok {
		r0 = returnFunc(tokens)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func([]int) error); ok {
		r1 = returnFunc(tokens)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenizer_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockTokenizer_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - tokens []int
func (_e *MockTokenizer_Expecter) Decode(tokens any) *MockTokenizer_Decode_Call {
	return &MockTokenizer_Decode_Call{Call: _e.mock.On("Decode", tokens)}
}

func (_c *MockTokenizer_Decode_Call) Run(run func(tokens []int)) *MockTokenizer_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int
		if args[0] != nil {
			arg0 = args[0].([]int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenizer_Decode_Call) Return(s string, err error) *MockTokenizer_Decode_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenizer_Decode_Call) RunAndReturn(run func(tokens []int) (string, error)) *MockTokenizer_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Encode provides a mock function for the type MockTokenizer
func (_mock *MockTokenizer) Encode(text string) ([]int, error) {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]int, error)); ok {
		return returnFunc(text)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []int); ok {
		r0 = returnFunc(text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenizer_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type MockTokenizer_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - text string
func (_e *MockTokenizer_Expecter) Encode(text any) *MockTokenizer_Encode_Call {
	return &MockTokenizer_Encode_Call{Call: _e.mock.On("Encode", text)}
}

func (_c *MockTokenizer_Encode_Call) Run(run func(text string)) *MockTokenizer_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenizer_Encode_Call) Return(ints []int, err error) *MockTokenizer_Encode_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockTokenizer_Encode_Call) RunAndReturn(run func(text string) ([]int, error)) *MockTokenizer_Encode_Call {
	_c.Call.Return(run)
	return _c
}
