// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileService creates a new instance of MockFileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileService {
	mock := &MockFileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileService is an autogenerated mock type for the FileService type
type MockFileService struct {
	mock.Mock
}

type MockFileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileService) EXPECT() *MockFileService_Expecter {
	return &MockFileService_Expecter{mock: &_m.Mock}
}

// GeneratePresignURL provides a mock function for the type MockFileService
func (_mock *MockFileService) GeneratePresignURL(ctx context.Context, param domain.GeneratePresignURLParam) (*domain.GeneratePresignURLReturn, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePresignURL")
	}

	var r0 *domain.GeneratePresignURLReturn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GeneratePresignURLParam) (*domain.GeneratePresignURLReturn, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GeneratePresignURLParam) *domain.GeneratePresignURLReturn); ok {
		r0 = returnFunc(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GeneratePresignURLReturn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.GeneratePresignURLParam) error); ok {
		r1 = returnFunc(ctx, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileService_GeneratePresignURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePresignURL'
type MockFileService_GeneratePresignURL_Call struct {
	*mock.Call
}

// GeneratePresignURL is a helper method to define mock.On call
//   - ctx context.Context
//   - param domain.GeneratePresignURLParam
func (_e *MockFileService_Expecter) GeneratePresignURL(ctx any, param any) *MockFileService_GeneratePresignURL_Call {
	return &MockFileService_GeneratePresignURL_Call{Call: _e.mock.On("GeneratePresignURL", ctx, param)}
}

func (_c *MockFileService_GeneratePresignURL_Call) Run(run func(ctx context.Context, param domain.GeneratePresignURLParam)) *MockFileService_GeneratePresignURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.GeneratePresignURLParam
		if args[1] != nil {
			arg1 = args[1].(domain.GeneratePresignURLParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileService_GeneratePresignURL_Call) Return(generatePresignURLReturn *domain.GeneratePresignURLReturn, err error) *MockFileService_GeneratePresignURL_Call {
	_c.Call.Return(generatePresignURLReturn, err)
	return _c
}

func (_c *MockFileService_GeneratePresignURL_Call) RunAndReturn(run func(ctx context.Context, param domain.GeneratePresignURLParam) (*domain.GeneratePresignURLReturn, error)) *MockFileService_GeneratePresignURL_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockFileService
func (_mock *MockFileService) Save(filename string, content io.Reader) (string, error) {
	ret := _mock.Called(filename, content)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, io.Reader) (string, error)); ok {
		return returnFunc(filename, content)
	}
	if returnFunc, ok := ret.Get(0).(func(string, io.Reader) string); ok {
		r0 = returnFunc(filename, content)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, io.Reader) error); ok {
		r1 = returnFunc(filename, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileService_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockFileService_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - filename string
//   - content io.Reader
func (_e *MockFileService_Expecter) Save(filename any, content any) *MockFileService_Save_Call {
	return &MockFileService_Save_Call{Call: _e.mock.On("Save", filename, content)}
}

func (_c *MockFileService_Save_Call) Run(run func(filename string, content io.Reader)) *MockFileService_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileService_Save_Call) Return(s string, err error) *MockFileService_Save_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileService_Save_Call) RunAndReturn(run func(filename string, content io.Reader) (string, error)) *MockFileService_Save_Call {
	_c.Call.Return(run)
	return _c
}
