// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/common"
	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJWTService creates a new instance of MockJWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTService {
	mock := &MockJWTService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJWTService is an autogenerated mock type for the JWTService type
type MockJWTService struct {
	mock.Mock
}

type MockJWTService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTService) EXPECT() *MockJWTService_Expecter {
	return &MockJWTService_Expecter{mock: &_m.Mock}
}

// IssueJWT provides a mock function for the type MockJWTService
func (_mock *MockJWTService) IssueJWT(ctx context.Context, userID int64, secret []byte) (string, error) {
	ret := _mock.Called(ctx, userID, secret)

	if len(ret) == 0 {
		panic("no return value specified for IssueJWT")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []byte) (string, error)); ok {
		return returnFunc(ctx, userID, secret)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []byte) string); ok {
		r0 = returnFunc(ctx, userID, secret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, []byte) error); ok {
		r1 = returnFunc(ctx, userID, secret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTService_IssueJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueJWT'
type MockJWTService_IssueJWT_Call struct {
	*mock.Call
}

// IssueJWT is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - secret []byte
func (_e *MockJWTService_Expecter) IssueJWT(ctx any, userID any, secret any) *MockJWTService_IssueJWT_Call {
	return &MockJWTService_IssueJWT_Call{Call: _e.mock.On("IssueJWT", ctx, userID, secret)}
}

func (_c *MockJWTService_IssueJWT_Call) Run(run func(ctx context.Context, userID int64, secret []byte)) *MockJWTService_IssueJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJWTService_IssueJWT_Call) Return(s string, err error) *MockJWTService_IssueJWT_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJWTService_IssueJWT_Call) RunAndReturn(run func(ctx context.Context, userID int64, secret []byte) (string, error)) *MockJWTService_IssueJWT_Call {
	_c.Call.Return(run)
	return _c
}

// IssueRefreshToken provides a mock function for the type MockJWTService
func (_mock *MockJWTService) IssueRefreshToken(ctx context.Context, param common.RefreshTokenParam) (string, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for IssueRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.RefreshTokenParam) (string, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, common.RefreshTokenParam) string); ok {
		r0 = returnFunc(ctx, param)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, common.RefreshTokenParam) error); ok {
		r1 = returnFunc(ctx, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTService_IssueRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueRefreshToken'
type MockJWTService_IssueRefreshToken_Call struct {
	*mock.Call
}

// IssueRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - param common.RefreshTokenParam
func (_e *MockJWTService_Expecter) IssueRefreshToken(ctx any, param any) *MockJWTService_IssueRefreshToken_Call {
	return &MockJWTService_IssueRefreshToken_Call{Call: _e.mock.On("IssueRefreshToken", ctx, param)}
}

func (_c *MockJWTService_IssueRefreshToken_Call) Run(run func(ctx context.Context, param common.RefreshTokenParam)) *MockJWTService_IssueRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 common.RefreshTokenParam
		if args[1] != nil {
			arg1 = args[1].(common.RefreshTokenParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJWTService_IssueRefreshToken_Call) Return(s string, err error) *MockJWTService_IssueRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJWTService_IssueRefreshToken_Call) RunAndReturn(run func(ctx context.Context, param common.RefreshTokenParam) (string, error)) *MockJWTService_IssueRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockJWTService
func (_mock *MockJWTService) Verify(token string) (domain.UserClaims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 domain.UserClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (domain.UserClaims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.UserClaims); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(domain.UserClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTService_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockJWTService_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - token string
func (_e *MockJWTService_Expecter) Verify(token any) *MockJWTService_Verify_Call {
	return &MockJWTService_Verify_Call{Call: _e.mock.On("Verify", token)}
}

func (_c *MockJWTService_Verify_Call) Run(run func(token string)) *MockJWTService_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJWTService_Verify_Call) Return(userClaims domain.UserClaims, err error) *MockJWTService_Verify_Call {
	_c.Call.Return(userClaims, err)
	return _c
}

func (_c *MockJWTService_Verify_Call) RunAndReturn(run func(token string) (domain.UserClaims, error)) *MockJWTService_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyRefreshToken provides a mock function for the type MockJWTService
func (_mock *MockJWTService) VerifyRefreshToken(ctx context.Context, token string) (domain.RefreshTokenClaims, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyRefreshToken")
	}

	var r0 domain.RefreshTokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.RefreshTokenClaims, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.RefreshTokenClaims); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(domain.RefreshTokenClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTService_VerifyRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyRefreshToken'
type MockJWTService_VerifyRefreshToken_Call struct {
	*mock.Call
}

// VerifyRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockJWTService_Expecter) VerifyRefreshToken(ctx any, token any) *MockJWTService_VerifyRefreshToken_Call {
	return &MockJWTService_VerifyRefreshToken_Call{Call: _e.mock.On("VerifyRefreshToken", ctx, token)}
}

func (_c *MockJWTService_VerifyRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockJWTService_VerifyRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJWTService_VerifyRefreshToken_Call) Return(refreshTokenClaims domain.RefreshTokenClaims, err error) *MockJWTService_VerifyRefreshToken_Call {
	_c.Call.Return(refreshTokenClaims, err)
	return _c
}

func (_c *MockJWTService_VerifyRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) (domain.RefreshTokenClaims, error)) *MockJWTService_VerifyRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
