// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockWebRenderer creates a new instance of MockWebRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebRenderer {
	mock := &MockWebRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebRenderer is an autogenerated mock type for the WebRenderer type
type MockWebRenderer struct {
	mock.Mock
}

type MockWebRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebRenderer) EXPECT() *MockWebRenderer_Expecter {
	return &MockWebRenderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function for the type MockWebRenderer
func (_mock *MockWebRenderer) Render(w http.ResponseWriter, name string, data any) {
	_mock.Called(w, name, data)
	return
}

// MockWebRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockWebRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - name string
//   - data any
func (_e *MockWebRenderer_Expecter) Render(w any, name any, data any) *MockWebRenderer_Render_Call {
	return &MockWebRenderer_Render_Call{Call: _e.mock.On("Render", w, name, data)}
}

func (_c *MockWebRenderer_Render_Call) Run(run func(w http.ResponseWriter, name string, data any)) *MockWebRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebRenderer_Render_Call) Return() *MockWebRenderer_Render_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebRenderer_Render_Call) RunAndReturn(run func(w http.ResponseWriter, name string, data any)) *MockWebRenderer_Render_Call {
	_c.Run(run)
	return _c
}

// Render2 provides a mock function for the type MockWebRenderer
func (_mock *MockWebRenderer) Render2(ctx context.Context, w http.ResponseWriter, name string, data map[string]any) {
	_mock.Called(ctx, w, name, data)
	return
}

// MockWebRenderer_Render2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render2'
type MockWebRenderer_Render2_Call struct {
	*mock.Call
}

// Render2 is a helper method to define mock.On call
//   - ctx context.Context
//   - w http.ResponseWriter
//   - name string
//   - data map[string]any
func (_e *MockWebRenderer_Expecter) Render2(ctx any, w any, name any, data any) *MockWebRenderer_Render2_Call {
	return &MockWebRenderer_Render2_Call{Call: _e.mock.On("Render2", ctx, w, name, data)}
}

func (_c *MockWebRenderer_Render2_Call) Run(run func(ctx context.Context, w http.ResponseWriter, name string, data map[string]any)) *MockWebRenderer_Render2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 http.ResponseWriter
		if args[1] != nil {
			arg1 = args[1].(http.ResponseWriter)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]any
		if args[3] != nil {
			arg3 = args[3].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWebRenderer_Render2_Call) Return() *MockWebRenderer_Render2_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebRenderer_Render2_Call) RunAndReturn(run func(ctx context.Context, w http.ResponseWriter, name string, data map[string]any)) *MockWebRenderer_Render2_Call {
	_c.Run(run)
	return _c
}
