// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChunkRepository creates a new instance of MockChunkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChunkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChunkRepository {
	mock := &MockChunkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChunkRepository is an autogenerated mock type for the ChunkRepository type
type MockChunkRepository struct {
	mock.Mock
}

type MockChunkRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChunkRepository) EXPECT() *MockChunkRepository_Expecter {
	return &MockChunkRepository_Expecter{mock: &_m.Mock}
}

// CountEmbeddedByFileID provides a mock function for the type MockChunkRepository
func (_mock *MockChunkRepository) CountEmbeddedByFileID(ctx context.Context, fileID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for CountEmbeddedByFileID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChunkRepository_CountEmbeddedByFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountEmbeddedByFileID'
type MockChunkRepository_CountEmbeddedByFileID_Call struct {
	*mock.Call
}

// CountEmbeddedByFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID uuid.UUID
func (_e *MockChunkRepository_Expecter) CountEmbeddedByFileID(ctx any, fileID any) *MockChunkRepository_CountEmbeddedByFileID_Call {
	return &MockChunkRepository_CountEmbeddedByFileID_Call{Call: _e.mock.On("CountEmbeddedByFileID", ctx, fileID)}
}

func (_c *MockChunkRepository_CountEmbeddedByFileID_Call) Run(run func(ctx context.Context, fileID uuid.UUID)) *MockChunkRepository_CountEmbeddedByFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChunkRepository_CountEmbeddedByFileID_Call) Return(n int, err error) *MockChunkRepository_CountEmbeddedByFileID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockChunkRepository_CountEmbeddedByFileID_Call) RunAndReturn(run func(ctx context.Context, fileID uuid.UUID) (int, error)) *MockChunkRepository_CountEmbeddedByFileID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByFileID provides a mock function for the type MockChunkRepository
func (_mock *MockChunkRepository) DeleteByFileID(ctx context.Context, fileID uuid.UUID) error {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByFileID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChunkRepository_DeleteByFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByFileID'
type MockChunkRepository_DeleteByFileID_Call struct {
	*mock.Call
}

// DeleteByFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID uuid.UUID
func (_e *MockChunkRepository_Expecter) DeleteByFileID(ctx any, fileID any) *MockChunkRepository_DeleteByFileID_Call {
	return &MockChunkRepository_DeleteByFileID_Call{Call: _e.mock.On("DeleteByFileID", ctx, fileID)}
}

func (_c *MockChunkRepository_DeleteByFileID_Call) Run(run func(ctx context.Context, fileID uuid.UUID)) *MockChunkRepository_DeleteByFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChunkRepository_DeleteByFileID_Call) Return(err error) *MockChunkRepository_DeleteByFileID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChunkRepository_DeleteByFileID_Call) RunAndReturn(run func(ctx context.Context, fileID uuid.UUID) error) *MockChunkRepository_DeleteByFileID_Call {
	_c.Call.Return(run)
	return _c
}

// StoreBatch provides a mock function for the type MockChunkRepository
func (_mock *MockChunkRepository) StoreBatch(ctx context.Context, chunks []domain.Chunk) error {
	ret := _mock.Called(ctx, chunks)

	if len(ret) == 0 {
		panic("no return value specified for StoreBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.Chunk) error); ok {
		r0 = returnFunc(ctx, chunks)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChunkRepository_StoreBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreBatch'
type MockChunkRepository_StoreBatch_Call struct {
	*mock.Call
}

// StoreBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - chunks []domain.Chunk
func (_e *MockChunkRepository_Expecter) StoreBatch(ctx any, chunks any) *MockChunkRepository_StoreBatch_Call {
	return &MockChunkRepository_StoreBatch_Call{Call: _e.mock.On("StoreBatch", ctx, chunks)}
}

func (_c *MockChunkRepository_StoreBatch_Call) Run(run func(ctx context.Context, chunks []domain.Chunk)) *MockChunkRepository_StoreBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.Chunk
		if args[1] != nil {
			arg1 = args[1].([]domain.Chunk)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChunkRepository_StoreBatch_Call) Return(err error) *MockChunkRepository_StoreBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChunkRepository_StoreBatch_Call) RunAndReturn(run func(ctx context.Context, chunks []domain.Chunk) error) *MockChunkRepository_StoreBatch_Call {
	_c.Call.Return(run)
	return _c
}
