// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFaqRepository creates a new instance of MockFaqRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFaqRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFaqRepository {
	mock := &MockFaqRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFaqRepository is an autogenerated mock type for the FaqRepository type
type MockFaqRepository struct {
	mock.Mock
}

type MockFaqRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFaqRepository) EXPECT() *MockFaqRepository_Expecter {
	return &MockFaqRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockFaqRepository
func (_mock *MockFaqRepository) Get(ctx context.Context, id uuid.UUID) (*domain.FAQ, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.FAQ
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.FAQ, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.FAQ); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FAQ)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFaqRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockFaqRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFaqRepository_Expecter) Get(ctx any, id any) *MockFaqRepository_Get_Call {
	return &MockFaqRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockFaqRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFaqRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFaqRepository_Get_Call) Return(fAQ *domain.FAQ, err error) *MockFaqRepository_Get_Call {
	_c.Call.Return(fAQ, err)
	return _c
}

func (_c *MockFaqRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.FAQ, error)) *MockFaqRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// SetLastIndexedHash provides a mock function for the type MockFaqRepository
func (_mock *MockFaqRepository) SetLastIndexedHash(ctx context.Context, id uuid.UUID, hash string) error {
	ret := _mock.Called(ctx, id, hash)

	if len(ret) == 0 {
		panic("no return value specified for SetLastIndexedHash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFaqRepository_SetLastIndexedHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLastIndexedHash'
type MockFaqRepository_SetLastIndexedHash_Call struct {
	*mock.Call
}

// SetLastIndexedHash is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - hash string
func (_e *MockFaqRepository_Expecter) SetLastIndexedHash(ctx any, id any, hash any) *MockFaqRepository_SetLastIndexedHash_Call {
	return &MockFaqRepository_SetLastIndexedHash_Call{Call: _e.mock.On("SetLastIndexedHash", ctx, id, hash)}
}

func (_c *MockFaqRepository_SetLastIndexedHash_Call) Run(run func(ctx context.Context, id uuid.UUID, hash string)) *MockFaqRepository_SetLastIndexedHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFaqRepository_SetLastIndexedHash_Call) Return(err error) *MockFaqRepository_SetLastIndexedHash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFaqRepository_SetLastIndexedHash_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, hash string) error) *MockFaqRepository_SetLastIndexedHash_Call {
	_c.Call.Return(run)
	return _c
}
