// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileService creates a new instance of MockFileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileService {
	mock := &MockFileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileService is an autogenerated mock type for the FileService type
type MockFileService struct {
	mock.Mock
}

type MockFileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileService) EXPECT() *MockFileService_Expecter {
	return &MockFileService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockFileService
func (_mock *MockFileService) Get(ctx context.Context, fileID uuid.UUID) (*domain.File, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.File, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.File); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockFileService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID uuid.UUID
func (_e *MockFileService_Expecter) Get(ctx any, fileID any) *MockFileService_Get_Call {
	return &MockFileService_Get_Call{Call: _e.mock.On("Get", ctx, fileID)}
}

func (_c *MockFileService_Get_Call) Run(run func(ctx context.Context, fileID uuid.UUID)) *MockFileService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileService_Get_Call) Return(file *domain.File, err error) *MockFileService_Get_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileService_Get_Call) RunAndReturn(run func(ctx context.Context, fileID uuid.UUID) (*domain.File, error)) *MockFileService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// SetEmbeddingStatus provides a mock function for the type MockFileService
func (_mock *MockFileService) SetEmbeddingStatus(ctx context.Context, fileID uuid.UUID, status domain.EmbeddingStatus) error {
	ret := _mock.Called(ctx, fileID, status)

	if len(ret) == 0 {
		panic("no return value specified for SetEmbeddingStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.EmbeddingStatus) error); ok {
		r0 = returnFunc(ctx, fileID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileService_SetEmbeddingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEmbeddingStatus'
type MockFileService_SetEmbeddingStatus_Call struct {
	*mock.Call
}

// SetEmbeddingStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID uuid.UUID
//   - status domain.EmbeddingStatus
func (_e *MockFileService_Expecter) SetEmbeddingStatus(ctx any, fileID any, status any) *MockFileService_SetEmbeddingStatus_Call {
	return &MockFileService_SetEmbeddingStatus_Call{Call: _e.mock.On("SetEmbeddingStatus", ctx, fileID, status)}
}

func (_c *MockFileService_SetEmbeddingStatus_Call) Run(run func(ctx context.Context, fileID uuid.UUID, status domain.EmbeddingStatus)) *MockFileService_SetEmbeddingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.EmbeddingStatus
		if args[2] != nil {
			arg2 = args[2].(domain.EmbeddingStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileService_SetEmbeddingStatus_Call) Return(err error) *MockFileService_SetEmbeddingStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileService_SetEmbeddingStatus_Call) RunAndReturn(run func(ctx context.Context, fileID uuid.UUID, status domain.EmbeddingStatus) error) *MockFileService_SetEmbeddingStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function for the type MockFileService
func (_mock *MockFileService) SetStatus(ctx context.Context, fileID uuid.UUID, status domain.UploadStatus) error {
	ret := _mock.Called(ctx, fileID, status)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.UploadStatus) error); ok {
		r0 = returnFunc(ctx, fileID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileService_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type MockFileService_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID uuid.UUID
//   - status domain.UploadStatus
func (_e *MockFileService_Expecter) SetStatus(ctx any, fileID any, status any) *MockFileService_SetStatus_Call {
	return &MockFileService_SetStatus_Call{Call: _e.mock.On("SetStatus", ctx, fileID, status)}
}

func (_c *MockFileService_SetStatus_Call) Run(run func(ctx context.Context, fileID uuid.UUID, status domain.UploadStatus)) *MockFileService_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.UploadStatus
		if args[2] != nil {
			arg2 = args[2].(domain.UploadStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileService_SetStatus_Call) Return(err error) *MockFileService_SetStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileService_SetStatus_Call) RunAndReturn(run func(ctx context.Context, fileID uuid.UUID, status domain.UploadStatus) error) *MockFileService_SetStatus_Call {
	_c.Call.Return(run)
	return _c
}
