// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/rag"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRagService creates a new instance of MockRagService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRagService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRagService {
	mock := &MockRagService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRagService is an autogenerated mock type for the RagService type
type MockRagService struct {
	mock.Mock
}

type MockRagService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRagService) EXPECT() *MockRagService_Expecter {
	return &MockRagService_Expecter{mock: &_m.Mock}
}

// BuildChunks provides a mock function for the type MockRagService
func (_mock *MockRagService) BuildChunks(ctx context.Context, source []byte) ([]rag.FinalChunk, error) {
	ret := _mock.Called(ctx, source)

	if len(ret) == 0 {
		panic("no return value specified for BuildChunks")
	}

	var r0 []rag.FinalChunk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]rag.FinalChunk, error)); ok {
		return returnFunc(ctx, source)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []rag.FinalChunk); ok {
		r0 = returnFunc(ctx, source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rag.FinalChunk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, source)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRagService_BuildChunks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildChunks'
type MockRagService_BuildChunks_Call struct {
	*mock.Call
}

// BuildChunks is a helper method to define mock.On call
//   - ctx context.Context
//   - source []byte
func (_e *MockRagService_Expecter) BuildChunks(ctx any, source any) *MockRagService_BuildChunks_Call {
	return &MockRagService_BuildChunks_Call{Call: _e.mock.On("BuildChunks", ctx, source)}
}

func (_c *MockRagService_BuildChunks_Call) Run(run func(ctx context.Context, source []byte)) *MockRagService_BuildChunks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRagService_BuildChunks_Call) Return(finalChunks []rag.FinalChunk, err error) *MockRagService_BuildChunks_Call {
	_c.Call.Return(finalChunks, err)
	return _c
}

func (_c *MockRagService_BuildChunks_Call) RunAndReturn(run func(ctx context.Context, source []byte) ([]rag.FinalChunk, error)) *MockRagService_BuildChunks_Call {
	_c.Call.Return(run)
	return _c
}
