// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorageClient creates a new instance of MockStorageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageClient {
	mock := &MockStorageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorageClient is an autogenerated mock type for the StorageClient type
type MockStorageClient struct {
	mock.Mock
}

type MockStorageClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageClient) EXPECT() *MockStorageClient_Expecter {
	return &MockStorageClient_Expecter{mock: &_m.Mock}
}

// DeleteObject provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) DeleteObject(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageClient_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockStorageClient_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageClient_Expecter) DeleteObject(ctx any, key any) *MockStorageClient_DeleteObject_Call {
	return &MockStorageClient_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, key)}
}

func (_c *MockStorageClient_DeleteObject_Call) Run(run func(ctx context.Context, key string)) *MockStorageClient_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageClient_DeleteObject_Call) Return(err error) *MockStorageClient_DeleteObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageClient_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockStorageClient_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectIntoBuffer provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) GetObjectIntoBuffer(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectIntoBuffer")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_GetObjectIntoBuffer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectIntoBuffer'
type MockStorageClient_GetObjectIntoBuffer_Call struct {
	*mock.Call
}

// GetObjectIntoBuffer is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageClient_Expecter) GetObjectIntoBuffer(ctx any, key any) *MockStorageClient_GetObjectIntoBuffer_Call {
	return &MockStorageClient_GetObjectIntoBuffer_Call{Call: _e.mock.On("GetObjectIntoBuffer", ctx, key)}
}

func (_c *MockStorageClient_GetObjectIntoBuffer_Call) Run(run func(ctx context.Context, key string)) *MockStorageClient_GetObjectIntoBuffer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageClient_GetObjectIntoBuffer_Call) Return(bytes []byte, err error) *MockStorageClient_GetObjectIntoBuffer_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockStorageClient_GetObjectIntoBuffer_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *MockStorageClient_GetObjectIntoBuffer_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresignGetURL provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) GetPresignGetURL(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignGetURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_GetPresignGetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignGetURL'
type MockStorageClient_GetPresignGetURL_Call struct {
	*mock.Call
}

// GetPresignGetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageClient_Expecter) GetPresignGetURL(ctx any, key any) *MockStorageClient_GetPresignGetURL_Call {
	return &MockStorageClient_GetPresignGetURL_Call{Call: _e.mock.On("GetPresignGetURL", ctx, key)}
}

func (_c *MockStorageClient_GetPresignGetURL_Call) Run(run func(ctx context.Context, key string)) *MockStorageClient_GetPresignGetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageClient_GetPresignGetURL_Call) Return(s string, err error) *MockStorageClient_GetPresignGetURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorageClient_GetPresignGetURL_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockStorageClient_GetPresignGetURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresignPutURL provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) GetPresignPutURL(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignPutURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_GetPresignPutURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignPutURL'
type MockStorageClient_GetPresignPutURL_Call struct {
	*mock.Call
}

// GetPresignPutURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageClient_Expecter) GetPresignPutURL(ctx any, key any) *MockStorageClient_GetPresignPutURL_Call {
	return &MockStorageClient_GetPresignPutURL_Call{Call: _e.mock.On("GetPresignPutURL", ctx, key)}
}

func (_c *MockStorageClient_GetPresignPutURL_Call) Run(run func(ctx context.Context, key string)) *MockStorageClient_GetPresignPutURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageClient_GetPresignPutURL_Call) Return(s string, err error) *MockStorageClient_GetPresignPutURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorageClient_GetPresignPutURL_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockStorageClient_GetPresignPutURL_Call {
	_c.Call.Return(run)
	return _c
}

// UploadObject provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) UploadObject(ctx context.Context, key string, mimeType string, buff []byte) error {
	ret := _mock.Called(ctx, key, mimeType, buff)

	if len(ret) == 0 {
		panic("no return value specified for UploadObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = returnFunc(ctx, key, mimeType, buff)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageClient_UploadObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadObject'
type MockStorageClient_UploadObject_Call struct {
	*mock.Call
}

// UploadObject is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - mimeType string
//   - buff []byte
func (_e *MockStorageClient_Expecter) UploadObject(ctx any, key any, mimeType any, buff any) *MockStorageClient_UploadObject_Call {
	return &MockStorageClient_UploadObject_Call{Call: _e.mock.On("UploadObject", ctx, key, mimeType, buff)}
}

func (_c *MockStorageClient_UploadObject_Call) Run(run func(ctx context.Context, key string, mimeType string, buff []byte)) *MockStorageClient_UploadObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorageClient_UploadObject_Call) Return(err error) *MockStorageClient_UploadObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageClient_UploadObject_Call) RunAndReturn(run func(ctx context.Context, key string, mimeType string, buff []byte) error) *MockStorageClient_UploadObject_Call {
	_c.Call.Return(run)
	return _c
}
