// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/anditakaesar/uwa-go-rag/internal/infra/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorageClient creates a new instance of MockStorageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageClient {
	mock := &MockStorageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorageClient is an autogenerated mock type for the StorageClient type
type MockStorageClient struct {
	mock.Mock
}

type MockStorageClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageClient) EXPECT() *MockStorageClient_Expecter {
	return &MockStorageClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) Get() *storage.S3Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *storage.S3Client
	if returnFunc, ok := ret.Get(0).(func() *storage.S3Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.S3Client)
		}
	}
	return r0
}

// MockStorageClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorageClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockStorageClient_Expecter) Get() *MockStorageClient_Get_Call {
	return &MockStorageClient_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockStorageClient_Get_Call) Run(run func()) *MockStorageClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageClient_Get_Call) Return(s3Client *storage.S3Client) *MockStorageClient_Get_Call {
	_c.Call.Return(s3Client)
	return _c
}

func (_c *MockStorageClient_Get_Call) RunAndReturn(run func() *storage.S3Client) *MockStorageClient_Get_Call {
	_c.Call.Return(run)
	return _c
}
