// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFAQService creates a new instance of MockFAQService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFAQService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFAQService {
	mock := &MockFAQService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFAQService is an autogenerated mock type for the FAQService type
type MockFAQService struct {
	mock.Mock
}

type MockFAQService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFAQService) EXPECT() *MockFAQService_Expecter {
	return &MockFAQService_Expecter{mock: &_m.Mock}
}

// Answer provides a mock function for the type MockFAQService
func (_mock *MockFAQService) Answer(ctx context.Context, id uuid.UUID, answer string, answeredBy int64) (*domain.FAQ, error) {
	ret := _mock.Called(ctx, id, answer, answeredBy)

	if len(ret) == 0 {
		panic("no return value specified for Answer")
	}

	var r0 *domain.FAQ
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int64) (*domain.FAQ, error)); ok {
		return returnFunc(ctx, id, answer, answeredBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int64) *domain.FAQ); ok {
		r0 = returnFunc(ctx, id, answer, answeredBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FAQ)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int64) error); ok {
		r1 = returnFunc(ctx, id, answer, answeredBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFAQService_Answer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Answer'
type MockFAQService_Answer_Call struct {
	*mock.Call
}

// Answer is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - answer string
//   - answeredBy int64
func (_e *MockFAQService_Expecter) Answer(ctx any, id any, answer any, answeredBy any) *MockFAQService_Answer_Call {
	return &MockFAQService_Answer_Call{Call: _e.mock.On("Answer", ctx, id, answer, answeredBy)}
}

func (_c *MockFAQService_Answer_Call) Run(run func(ctx context.Context, id uuid.UUID, answer string, answeredBy int64)) *MockFAQService_Answer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFAQService_Answer_Call) Return(fAQ *domain.FAQ, err error) *MockFAQService_Answer_Call {
	_c.Call.Return(fAQ, err)
	return _c
}

func (_c *MockFAQService_Answer_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, answer string, answeredBy int64) (*domain.FAQ, error)) *MockFAQService_Answer_Call {
	_c.Call.Return(run)
	return _c
}

// ListUnanswered provides a mock function for the type MockFAQService
func (_mock *MockFAQService) ListUnanswered(ctx context.Context, limit int, offset int) ([]domain.FAQ, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListUnanswered")
	}

	var r0 []domain.FAQ
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]domain.FAQ, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []domain.FAQ); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FAQ)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFAQService_ListUnanswered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUnanswered'
type MockFAQService_ListUnanswered_Call struct {
	*mock.Call
}

// ListUnanswered is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockFAQService_Expecter) ListUnanswered(ctx any, limit any, offset any) *MockFAQService_ListUnanswered_Call {
	return &MockFAQService_ListUnanswered_Call{Call: _e.mock.On("ListUnanswered", ctx, limit, offset)}
}

func (_c *MockFAQService_ListUnanswered_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockFAQService_ListUnanswered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFAQService_ListUnanswered_Call) Return(fAQs []domain.FAQ, err error) *MockFAQService_ListUnanswered_Call {
	_c.Call.Return(fAQs, err)
	return _c
}

func (_c *MockFAQService_ListUnanswered_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]domain.FAQ, error)) *MockFAQService_ListUnanswered_Call {
	_c.Call.Return(run)
	return _c
}
