// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFAQService creates a new instance of MockFAQService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFAQService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFAQService {
	mock := &MockFAQService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFAQService is an autogenerated mock type for the FAQService type
type MockFAQService struct {
	mock.Mock
}

type MockFAQService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFAQService) EXPECT() *MockFAQService_Expecter {
	return &MockFAQService_Expecter{mock: &_m.Mock}
}

// Answer provides a mock function for the type MockFAQService
func (_mock *MockFAQService) Answer(ctx context.Context, id uuid.UUID, answer string, answeredBy int64) (*domain.FAQ, error) {
	ret := _mock.Called(ctx, id, answer, answeredBy)

	if len(ret) == 0 {
		panic("no return value specified for Answer")
	}

	var r0 *domain.FAQ
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int64) (*domain.FAQ, error)); ok {
		return returnFunc(ctx, id, answer, answeredBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int64) *domain.FAQ); ok {
		r0 = returnFunc(ctx, id, answer, answeredBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FAQ)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int64) error); ok {
		r1 = returnFunc(ctx, id, answer, answeredBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFAQService_Answer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Answer'
type MockFAQService_Answer_Call struct {
	*mock.Call
}

// Answer is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - answer string
//   - answeredBy int64
func (_e *MockFAQService_Expecter) Answer(ctx any, id any, answer any, answeredBy any) *MockFAQService_Answer_Call {
	return &MockFAQService_Answer_Call{Call: _e.mock.On("Answer", ctx, id, answer, answeredBy)}
}

func (_c *MockFAQService_Answer_Call) Run(run func(ctx context.Context, id uuid.UUID, answer string, answeredBy int64)) *MockFAQService_Answer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFAQService_Answer_Call) Return(fAQ *domain.FAQ, err error) *MockFAQService_Answer_Call {
	_c.Call.Return(fAQ, err)
	return _c
}

func (_c *MockFAQService_Answer_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, answer string, answeredBy int64) (*domain.FAQ, error)) *MockFAQService_Answer_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockFAQService
func (_mock *MockFAQService) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFAQService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFAQService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFAQService_Expecter) Delete(ctx any, id any) *MockFAQService_Delete_Call {
	return &MockFAQService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockFAQService_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFAQService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFAQService_Delete_Call) Return(err error) *MockFAQService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFAQService_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockFAQService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockFAQService
func (_mock *MockFAQService) List(ctx context.Context, param *domain.FetchFAQParam) ([]domain.FAQ, error) {
	ret := _mock.Called(ctx, param)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.FAQ
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.FetchFAQParam) ([]domain.FAQ, error)); ok {
		return returnFunc(ctx, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.FetchFAQParam) []domain.FAQ); ok {
		r0 = returnFunc(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FAQ)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.FetchFAQParam) error); ok {
		r1 = returnFunc(ctx, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFAQService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFAQService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - param *domain.FetchFAQParam
func (_e *MockFAQService_Expecter) List(ctx any, param any) *MockFAQService_List_Call {
	return &MockFAQService_List_Call{Call: _e.mock.On("List", ctx, param)}
}

func (_c *MockFAQService_List_Call) Run(run func(ctx context.Context, param *domain.FetchFAQParam)) *MockFAQService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.FetchFAQParam
		if args[1] != nil {
			arg1 = args[1].(*domain.FetchFAQParam)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFAQService_List_Call) Return(fAQs []domain.FAQ, err error) *MockFAQService_List_Call {
	_c.Call.Return(fAQs, err)
	return _c
}

func (_c *MockFAQService_List_Call) RunAndReturn(run func(ctx context.Context, param *domain.FetchFAQParam) ([]domain.FAQ, error)) *MockFAQService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockFAQService
func (_mock *MockFAQService) Update(ctx context.Context, id uuid.UUID, param *domain.UpdateFAQParam) (*domain.FAQ, error) {
	ret := _mock.Called(ctx, id, param)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.FAQ
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateFAQParam) (*domain.FAQ, error)); ok {
		return returnFunc(ctx, id, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateFAQParam) *domain.FAQ); ok {
		r0 = returnFunc(ctx, id, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FAQ)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.UpdateFAQParam) error); ok {
		r1 = returnFunc(ctx, id, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFAQService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFAQService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - param *domain.UpdateFAQParam
func (_e *MockFAQService_Expecter) Update(ctx any, id any, param any) *MockFAQService_Update_Call {
	return &MockFAQService_Update_Call{Call: _e.mock.On("Update", ctx, id, param)}
}

func (_c *MockFAQService_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, param *domain.UpdateFAQParam)) *MockFAQService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *domain.UpdateFAQParam
		if args[2] != nil {
			arg2 = args[2].(*domain.UpdateFAQParam)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFAQService_Update_Call) Return(fAQ *domain.FAQ, err error) *MockFAQService_Update_Call {
	_c.Call.Return(fAQ, err)
	return _c
}

func (_c *MockFAQService_Update_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, param *domain.UpdateFAQParam) (*domain.FAQ, error)) *MockFAQService_Update_Call {
	_c.Call.Return(run)
	return _c
}
