// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anditakaesar/uwa-go-rag/internal/worker"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJobQueue creates a new instance of MockJobQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobQueue {
	mock := &MockJobQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobQueue is an autogenerated mock type for the JobQueue type
type MockJobQueue struct {
	mock.Mock
}

type MockJobQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobQueue) EXPECT() *MockJobQueue_Expecter {
	return &MockJobQueue_Expecter{mock: &_m.Mock}
}

// EnqueueIndexFaq provides a mock function for the type MockJobQueue
func (_mock *MockJobQueue) EnqueueIndexFaq(ctx context.Context, args worker.IndexFaqArgs) error {
	ret := _mock.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueIndexFaq")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, worker.IndexFaqArgs) error); ok {
		r0 = returnFunc(ctx, args)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobQueue_EnqueueIndexFaq_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueIndexFaq'
type MockJobQueue_EnqueueIndexFaq_Call struct {
	*mock.Call
}

// EnqueueIndexFaq is a helper method to define mock.On call
//   - ctx context.Context
//   - args worker.IndexFaqArgs
func (_e *MockJobQueue_Expecter) EnqueueIndexFaq(ctx any, args any) *MockJobQueue_EnqueueIndexFaq_Call {
	return &MockJobQueue_EnqueueIndexFaq_Call{Call: _e.mock.On("EnqueueIndexFaq", ctx, args)}
}

func (_c *MockJobQueue_EnqueueIndexFaq_Call) Run(run func(ctx context.Context, args worker.IndexFaqArgs)) *MockJobQueue_EnqueueIndexFaq_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 worker.IndexFaqArgs
		if args[1] != nil {
			arg1 = args[1].(worker.IndexFaqArgs)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobQueue_EnqueueIndexFaq_Call) Return(err error) *MockJobQueue_EnqueueIndexFaq_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobQueue_EnqueueIndexFaq_Call) RunAndReturn(run func(ctx context.Context, args worker.IndexFaqArgs) error) *MockJobQueue_EnqueueIndexFaq_Call {
	_c.Call.Return(run)
	return _c
}
