// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/anditakaesar/uwa-go-rag/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Answer provides a mock function for the type MockRepository
func (_mock *MockRepository) Answer(ctx context.Context, id uuid.UUID, answer string, answeredBy int64, now time.Time) (*domain.FAQ, error) {
	ret := _mock.Called(ctx, id, answer, answeredBy, now)

	if len(ret) == 0 {
		panic("no return value specified for Answer")
	}

	var r0 *domain.FAQ
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int64, time.Time) (*domain.FAQ, error)); ok {
		return returnFunc(ctx, id, answer, answeredBy, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int64, time.Time) *domain.FAQ); ok {
		r0 = returnFunc(ctx, id, answer, answeredBy, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FAQ)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int64, time.Time) error); ok {
		r1 = returnFunc(ctx, id, answer, answeredBy, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Answer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Answer'
type MockRepository_Answer_Call struct {
	*mock.Call
}

// Answer is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - answer string
//   - answeredBy int64
//   - now time.Time
func (_e *MockRepository_Expecter) Answer(ctx any, id any, answer any, answeredBy any, now any) *MockRepository_Answer_Call {
	return &MockRepository_Answer_Call{Call: _e.mock.On("Answer", ctx, id, answer, answeredBy, now)}
}

func (_c *MockRepository_Answer_Call) Run(run func(ctx context.Context, id uuid.UUID, answer string, answeredBy int64, now time.Time)) *MockRepository_Answer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_Answer_Call) Return(fAQ *domain.FAQ, err error) *MockRepository_Answer_Call {
	_c.Call.Return(fAQ, err)
	return _c
}

func (_c *MockRepository_Answer_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, answer string, answeredBy int64, now time.Time) (*domain.FAQ, error)) *MockRepository_Answer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFile provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateFile(ctx context.Context, faqID uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, faqID)

	if len(ret) == 0 {
		panic("no return value specified for CreateFile")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, faqID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, faqID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, faqID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFile'
type MockRepository_CreateFile_Call struct {
	*mock.Call
}

// CreateFile is a helper method to define mock.On call
//   - ctx context.Context
//   - faqID uuid.UUID
func (_e *MockRepository_Expecter) CreateFile(ctx any, faqID any) *MockRepository_CreateFile_Call {
	return &MockRepository_CreateFile_Call{Call: _e.mock.On("CreateFile", ctx, faqID)}
}

func (_c *MockRepository_CreateFile_Call) Run(run func(ctx context.Context, faqID uuid.UUID)) *MockRepository_CreateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateFile_Call) Return(uUID uuid.UUID, err error) *MockRepository_CreateFile_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockRepository_CreateFile_Call) RunAndReturn(run func(ctx context.Context, faqID uuid.UUID) (uuid.UUID, error)) *MockRepository_CreateFile_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUnanswered provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateUnanswered(ctx context.Context, newFAQ domain.FAQ) error {
	ret := _mock.Called(ctx, newFAQ)

	if len(ret) == 0 {
		panic("no return value specified for CreateUnanswered")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FAQ) error); ok {
		r0 = returnFunc(ctx, newFAQ)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateUnanswered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUnanswered'
type MockRepository_CreateUnanswered_Call struct {
	*mock.Call
}

// CreateUnanswered is a helper method to define mock.On call
//   - ctx context.Context
//   - newFAQ domain.FAQ
func (_e *MockRepository_Expecter) CreateUnanswered(ctx any, newFAQ any) *MockRepository_CreateUnanswered_Call {
	return &MockRepository_CreateUnanswered_Call{Call: _e.mock.On("CreateUnanswered", ctx, newFAQ)}
}

func (_c *MockRepository_CreateUnanswered_Call) Run(run func(ctx context.Context, newFAQ domain.FAQ)) *MockRepository_CreateUnanswered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FAQ
		if args[1] != nil {
			arg1 = args[1].(domain.FAQ)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateUnanswered_Call) Return(err error) *MockRepository_CreateUnanswered_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateUnanswered_Call) RunAndReturn(run func(ctx context.Context, newFAQ domain.FAQ) error) *MockRepository_CreateUnanswered_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) Delete(ctx any, id any) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(ctx context.Context, id uuid.UUID) (*domain.FAQ, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.FAQ
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.FAQ, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.FAQ); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FAQ)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) Get(ctx any, id any) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(fAQ *domain.FAQ, err error) *MockRepository_Get_Call {
	_c.Call.Return(fAQ, err)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.FAQ, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) ListByStatus(ctx context.Context, status domain.FAQStatus, limit int, offset int) ([]domain.FAQ, error) {
	ret := _mock.Called(ctx, status, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByStatus")
	}

	var r0 []domain.FAQ
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FAQStatus, int, int) ([]domain.FAQ, error)); ok {
		return returnFunc(ctx, status, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FAQStatus, int, int) []domain.FAQ); ok {
		r0 = returnFunc(ctx, status, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FAQ)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FAQStatus, int, int) error); ok {
		r1 = returnFunc(ctx, status, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByStatus'
type MockRepository_ListByStatus_Call struct {
	*mock.Call
}

// ListByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status domain.FAQStatus
//   - limit int
//   - offset int
func (_e *MockRepository_Expecter) ListByStatus(ctx any, status any, limit any, offset any) *MockRepository_ListByStatus_Call {
	return &MockRepository_ListByStatus_Call{Call: _e.mock.On("ListByStatus", ctx, status, limit, offset)}
}

func (_c *MockRepository_ListByStatus_Call) Run(run func(ctx context.Context, status domain.FAQStatus, limit int, offset int)) *MockRepository_ListByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FAQStatus
		if args[1] != nil {
			arg1 = args[1].(domain.FAQStatus)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_ListByStatus_Call) Return(fAQs []domain.FAQ, err error) *MockRepository_ListByStatus_Call {
	_c.Call.Return(fAQs, err)
	return _c
}

func (_c *MockRepository_ListByStatus_Call) RunAndReturn(run func(ctx context.Context, status domain.FAQStatus, limit int, offset int) ([]domain.FAQ, error)) *MockRepository_ListByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetLastIndexedHash provides a mock function for the type MockRepository
func (_mock *MockRepository) SetLastIndexedHash(ctx context.Context, id uuid.UUID, hash string) error {
	ret := _mock.Called(ctx, id, hash)

	if len(ret) == 0 {
		panic("no return value specified for SetLastIndexedHash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetLastIndexedHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLastIndexedHash'
type MockRepository_SetLastIndexedHash_Call struct {
	*mock.Call
}

// SetLastIndexedHash is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - hash string
func (_e *MockRepository_Expecter) SetLastIndexedHash(ctx any, id any, hash any) *MockRepository_SetLastIndexedHash_Call {
	return &MockRepository_SetLastIndexedHash_Call{Call: _e.mock.On("SetLastIndexedHash", ctx, id, hash)}
}

func (_c *MockRepository_SetLastIndexedHash_Call) Run(run func(ctx context.Context, id uuid.UUID, hash string)) *MockRepository_SetLastIndexedHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SetLastIndexedHash_Call) Return(err error) *MockRepository_SetLastIndexedHash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetLastIndexedHash_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, hash string) error) *MockRepository_SetLastIndexedHash_Call {
	_c.Call.Return(run)
	return _c
}
